### ISSUE TITLE
[documentation] ignore block

### ISSUE THREAD

**Issue by glaucocustodio** [thoughtbot/factory_girl#1000]
Is there any documentation to the `ignore` block? I didn't find on `GETTING_STARTED.md`.

It seems to be useful in some cases. I can help writing one if I am told what should I write..

Thanks.

**Comment by joshuaclayton** [comment]
@glaucocustodio yep; the name actually changed to `transient`, and you can read more about it [here](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#transient-attributes). Best of luck!

**Comment by glaucocustodio** [comment]
`transient` I know! 

Should we add to the documentation that it is the former `ignore`? It may help someone coming from stackoverflow xD.
