### ISSUE TITLE
Question: How to build a model that has at least one in has_many?

### ISSUE THREAD

**Issue by pedroadame** [thoughtbot/factory_girl#1008]
According to documentation, I built this for a has_many:

```ruby
# app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  validates :text, presence: true
  validates :answers, length: { minimum: 1 }
end
```

```ruby
# app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :text, presence: true
end
```

```ruby
# spec/factories.rb
...
factory :question do
  text "Sample text"
  transient do
    answer_count 2
  end

  after(:create) do |question, evaluator|
    create_list(:answer, evaluator.answer_count, question: question)
  end
end

factory :answer do
  text "Sample answer"
end
```

But it fails with a `RecordInvalid` error when I try to `create(:question)` due to the association length validation in `question.rb`. How can I achieve this?

**Comment by meaganewaller** [comment]
Hi! You've probably already figured out the answer answer to this already, so maybe this will help someone else wondering the same thing. 

Changing `after(:create)` to  `after(:build)` will ensure that `answer` exists to be validated before creating the `question`. 

😄

**Comment by pedroadame** [comment]
Yes @meaganewaller, I figured it out. The answer to do that correctly was changing the `after(:create)` to:
```
after(:build) do |question, evaluator|
  question.answers = build_list(:answer, evaluator.answer_count, question: question)
end
```
