### ISSUE TITLE
ArticleTest#test_should_be_invalid_without_title: NoMethodError: undefined method `article' for #<Article:0x005608ecac55a8>     test/models/article_test.rb:6:in `block in <class:ArticleTest>'

### ISSUE THREAD

**Issue by abhinav098** [thoughtbot/factory_girl#1020]
Error with the Factory girl ..with minitest-rails

**test_helper.rb**

ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
 include FactoryGirl::Syntax::Methods
  # Add more helper methods to be used by all tests here...
end

**/test/factories/article.rb**

FactoryGirl.define do
  factory :article do
    title "Title"
    body  "Body number one"
  end
end

**article_test.rb:**

require 'test_helper'

class ArticleTest < ActiveSupport::TestCase

  test "should be invalid without title" do
    @article=create(:article, title: "")
    assert_nil @article.title
    assert_equal false, @article.valid?
  end

  # test "should be invalid without body" do
  # end

  # test "should be valid" do
  # end

  # test "article body should be string" do
  # end

  # test "article title should be string" do
  # end

end

**Comment by odlp** [comment]
Hey @abhinav098 - it's a bit hard to tell from the code you've provided. One thing I noticed is this line has an instance variable with a capital 'A': `@Article=create(:article, title: "")` but your other references use a lowercase 'a': `@article`.

Perhaps you could edit the issue and format the code. By surrounding your blocks of code with three backticks at the start and the end (```). This will improve the legibility of your example.

Please see: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
