### ISSUE TITLE
Sequences not returning unique value

### ISSUE THREAD

**Issue by laclance** [thoughtbot/factory_girl#1028]
My model tests used to pass, I have not changed them and now they fail with "name already exists".
I have looked at and tried many solutions but have not found one that works. Also tried using instance variables in my test and moving instantiation to different blocks, before, it, describe and context.

```
FactoryGirl.define do
  factory :activity do
    sequence(:name) { |n| "name_#{n}" }
  end
end
```

```
RSpec.describe Activity do
  let(:activity) { FactoryGirl.create :activity }

  it "has a valid factory" do
    expect(activity).to be_valid
  end
end
```

rspec-rails > 3.5
factory_girl_rails > 4.8
ruby > 2.3.3
rails > 4.2.0

**Comment by novito** [comment]
I think your problem is not related to FactoryGirl, but rather the fact that your database might not be getting cleaned up. Can you double check that the `activities` table is empty before the test that is failing?

**Comment by laclance** [comment]
Thank you for your response. Its working now. That was probably the problem i was fiddling around with rails_helper and spec_helper. My apologies.
