### ISSUE TITLE
Changes to array attributes affects other factory objects

### ISSUE THREAD

**Issue by joshua5201** [thoughtbot/factory_girl#1030]
Hi,
I encountered this problem when working on my project. I've made an example here to reproduce it.

Environment: 
Rails 5.1
Ruby 2.4.1
ArchLinux
Rspec 3.6.0
Factory Girl 4.8.0

This is a simple pure Ruby class
app/models/cart.rb
```ruby
class Cart
  attr_accessor :items

  def initialize
    @items = []
  end 

  def double!
    items.map! { |i| i * 2 } 
  end 
end
```

Try in rails console:
```
2.4.1 :001 > c = Cart.new
 => #<Cart:0x00000002ce84f0 @items=[]> 
2.4.1 :002 > c.items = [1,2,3]
 => [1, 2, 3] 
2.4.1 :003 > c2 = Cart.new
 => #<Cart:0x00000002c95598 @items=[]> 
2.4.1 :004 > c2.items = [1,2,3]
 => [1, 2, 3] 
2.4.1 :005 > c2.double!
 => [2, 4, 6] 
2.4.1 :006 > c
 => #<Cart:0x00000002ce84f0 @items=[1, 2, 3]> 
2.4.1 :007 > c.items
 => [1, 2, 3] 
```

The objects behave as expected

but this test failed:

spec/models/cart_spec.rb
```ruby
require 'rails_helper'

RSpec.describe Cart do
  describe '#double!' do
    let (:cart1) { FactoryGirl.build(:cart) }
    let (:cart2) { FactoryGirl.build(:cart) }

    it "doubles the elements in items" do
      cart1.double!
      expect(cart1.items).to eq([2, 4, 6]) 
    end 

    it "remains the same if do nothing" do
      expect(cart2.items).to eq([1, 2, 3]) 
    end 
  end 
end

```

with factory defined:
```ruby
FactoryGirl.define do
  factory :cart do
    items [1, 2, 3]
  end
end
```

```
  1) Cart#double! remains the same if do nothing
     Failure/Error: expect(cart2.items).to eq([1, 2, 3])
     
       expected: [1, 2, 3]
            got: [2, 4, 6]
     
       (compared using ==)
     # ./spec/models/cart_spec.rb:14:in `block (3 levels) in <top (required)>'

```

If I put byebug in the second example
```
    9:       cart1.double!
   10:       expect(cart1.items).to eq([2, 4, 6])
   11:     end
   12: 
   13:     it "remains the same if do nothing" do
   14:       byebug
=> 15:       expect(cart2.items).to eq([1, 2, 3])
   16:     end
   17:   end
   18: end
(byebug) cart2
#<Cart:0x000000033b8938 @items=[2, 4, 6]>
(byebug) cart1
#<Cart:0x000000033b3e60 @items=[2, 4, 6]>
(byebug) cart1.double!
[4, 8, 12]
(byebug) cart2
#<Cart:0x000000033b8938 @items=[4, 8, 12]>
```
the 2 carts have different object id but the #double! affected both objects. Also tried using FactoryGirl.build in rails console, and the results were the same.

Is this a feature or bug?
I've tried tracing the repo's source but didn't know how to figure it out. It will be really good if someone points out the related class / method then I can understand the source.

Thanks

**Comment by odlp** [comment]
Hi @joshua5201,

The current factory definition is using static values, so when the code mutates with `#map!` it affects all instances created with the factory.

If you update the factory definition to use [dynamic attributes](http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Dynamic_Attributes) this should resolve your issue:

```ruby
FactoryGirl.define do
  factory :cart do
    items { [1, 2, 3] }
  end
end
```

By providing a block to FactoryGirl, this will be called when creating each instance of `cart`, giving you a distinct array.

Hope this helps!

**Comment by joshua5201** [comment]
Thanks a lot!
So we can close this issue?
