### ISSUE TITLE
[bug] after_commit fires every time on associations when I use .create

### ISSUE THREAD

**Issue by kesha-antonov** [thoughtbot/factory_girl#1031]
Hello!

```
user = FactoryGirl.create(:user)
other_model = FactoryGirl.create(:other_model, user: user)
```

When FactoryGirl creates ```other_model``` ```after_commit``` in ```User``` model fires every time. It's ok. But arguments is wrong. I see in ```self.previous_changes``` of ```user``` attributes that was used for new_record. For example, ```id: [nil, 1]```

If I do
```
5.times do
  FactoryGirl.create(:other_model, user: user)
end
```
then ```after_update_commit``` in ```User``` will be fired 5 times with ```self.previous_changes``` like above ```id: [nil, 1], ...```

What am I doing wrong?

Thanks!

**Comment by joshuaclayton** [comment]
@kesha-antonov it looks like there's some coupling between the two models; I was able to put together a simple example demonstrating that the behavior works as expected:

```ruby
describe "ActiveRecord callbacks" do
  include FactoryGirl::Syntax::Methods

  before do
    define_model('Post', title: :string, user_id: :integer) do
      belongs_to :user
    end

    define_model('User', name: :string) do
      after_update_commit do
        raise "got here"
      end
    end

    FactoryGirl.define do
      factory :user
      factory :post
    end
  end

  it "doesn't unnecessarily trigger after_update_commit" do
    user = create(:user)

    5.times do
      create(:post, user: user)
    end

    expect(user.previous_changes["id"]).to eq [nil, user.id]
  end
end
```

Coincidentally, I was also able to get this example to fail (have it raise in the `after_update_commit` by adding a `touch: true` to the association on `Post`. My guess is that there's some additional code within your application that's causing one record to update the other in a not-necessarily-obvious fashion.

Best of luck!

**Comment by fedefa** [comment]
Same issue for mi, tokens inline association trigger after_create_commit and pass a user without "identities" association. So tests behaviour is really unpredictable. 

```
factory :user, class: User do
  tokens { [association(:token, user: instance)] }
  identities { [association(:identities, user: instance)] }
end
```

My only option was to put associations inside after_create block instead as inline.

Please help,
Thank you!
