### ISSUE TITLE
Object id from the created factory not correct.

### ISSUE THREAD

**Issue by carlosguerreroo** [thoughtbot/factory_girl#1045]
I'm using factory girl to create a new object (`Dish`), but when I try to get the id of the new object is giving a incorrect id (An Id that is not actually on the database). After a few moments of debugging I discovered It's actually giving me the id of the association (in this case the `User`)

Example:
```
user  = FactoryGirl.create :user
dish = FactoryGirl.create(:dish, user: user)
```

If I print the object the id value is nil, but the object is actually saved on the database.

```
#<Dish:0x007ff68b8710e8
 id: nil,
 name: "Pork belly buns",
 description: "Delectus sed in sint aliquid rerum maiores.",
 price: 5000,
 image: "nullahicdoloremque.png",
 user_id: 5,
 created_at: Wed, 04 Oct 2017 12:37:24 CDT -05:00,
 updated_at: Wed, 04 Oct 2017 12:37:24 CDT -05:00,
 category_id: 9,
 extra_drinks_included: 0,
 extra_food_included: 0,
 deleted_at: nil,
 promoted: false,
 preparation_time: 12>
```

**Comment by salimane** [comment]
@carlosguerreroo how did you solve this problem ?

**Comment by ral-wtag** [comment]
@carlosguerreroo  how this problem was solved? I am facing a similar issue with FactoryBot.

```
u = FactoryBot.create(:user, nick_name: 'test', mobile_number: '+41216931110', role: :admin)

=> #<User id: nil, 
full_name: "TestUser", 
nick_name: "test", 
mobile_number: "+41216931110", 
company_id: 1>
```
