### ISSUE TITLE
Undefined method `lint' for FactoryGirl:Module (NoMethodError)

### ISSUE THREAD

**Issue by christhesoul** [thoughtbot/factory_girl#610]
Hi

I'm really struggling with this. I'm trying to follow the documentation exactly, because I'm sure it must be my mistake, but I just cannot get `lint` working.

My gem file current looks like this:

```ruby
group :test do
  gem "factory_girl_rails", "4.0"
  gem 'capybara'
  gem 'guard-rspec'
  gem 'rb-fsevent', '~> 0.9'
  gem "database_cleaner", "~> 1.2.0"
end
```

And I have in `spec/support/factory_girl.rb`

```ruby
RSpec.configure do |config|
  # additional factory_girl configuration
  config.include FactoryGirl::Syntax::Methods

  config.before(:suite) do
    FactoryGirl.lint
  end
end
```

Yet every time I fire up `bundle exec guard`, I'm told that there is an `undefined method 'lint' for FactoryGirl:Module (NoMethodError)`

Similarly, if I fire up my test console, I get the same.

(Factory Girl is loading because I can build, create etc)

I've tried FactoryGirl 4.0 and 4.3 in my Gemfile.

Perhaps lint isn't available for factory_girl_rails? I'm at a loss. Any help would be appreciated!

**Comment by artemdev** [comment]
thanks!
