### ISSUE TITLE
Testing associations fails using every FactoryGirl syntax

### ISSUE THREAD

**Issue by reconstructions** [thoughtbot/factory_girl#612]
I have tried about at least 10 different syntaxes and proposed solutions to the problem of testing associations in FactoryGirl:

[Checking ActiveRecord Associations in RSpec](http://stackoverflow.com/questions/2673041/checking-activerecord-associations-in-rspec)

[Thoughtbot - Associations](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md)

[Factory Girl Callbacks](http://robots.thoughtbot.com/aint-no-calla-back-girl)

[add_collection_associations_to_factory_girl_factories.rb](https://gist.github.com/ybart/8844969)

[Using factory girl to create HABTM association](http://stackoverflow.com/questions/21651277/using-factory-girl-to-create-habtm-association/21651974#21651974)

[Everyday Rails Testing with RSpec](http://everydayrails.com)

[Problems with factory_girl and has_many / belongs_to associations](https://github.com/thoughtbot/factory_girl/issues/549)

[FactoryGirl and has_many associations](http://icelab.com.au/articles/factorygirl-and-has-many-associations/)

[Populating an association with children in factory_girl](http://stackoverflow.com/questions/2937326/populating-an-association-with-children-in-factory-girl)

[ActiveRecord::AssociationTypeMismatch when trying to build an association](https://github.com/thoughtbot/factory_girl/issues/608)

This selection of proposed solutions spans at least a couple years, and during this time FactoryGirl syntax has continually changed.  If any of these solutions ever worked, they don't work with the current version.  I tried them all, and none of them worked with Rails 4, factory_girl_rails 4.4.0, and rspec-rails 2.14.1.

From this I conclude that FactoryGirl has either 1) never been able to test associations, or 2) changes its syntax continually so that as soon as someone figures out how to use it to test associations, the syntax changes and breaks the previous solution.

This fails for me:

My spec/factories.rb

```ruby
FactoryGirl.define do
  factory :instrument do
  end

  factory :musician do
    ignore do
      instrument_count 1
    end

    after :build do |musician, evaluator|
      evaluator.instrument_count.times do
        musician.instruments << build(:instrument)
      end
    end
  end
end
```

My musician.rb model class:
 ```ruby
    class Musician < ActiveRecord::Base
      has_many :instruments

      validate :has_instrument

      def has_instrument
        unless self.instruments.exists?
          self.errors.add :base, "Each musician should have at least one instrument"
        end
      end
    end
```
My spec/models/musician_spec.rb
```ruby
    @squirrelgator_mu = FactoryGirl.create(:musician)
```
The console error:
```ruby
    4) Musician belongs to a User
       Failure/Error: @squirrelgator_mu = FactoryGirl.create(:musician)  ######
       ActiveRecord::RecordInvalid:
         Validation failed: Each musician should have at least one instrument
       # ./spec/models/musician_spec.rb:11:in `block (2 levels) in <top (required)>'
```
This is just the [latest proposed solution](https://github.com/thoughtbot/factory_girl/issues/608), but like all the others it breaks for me.

**Comment by unkmas** [comment]
@reconstructions hi! Could you tell me, have you found a solution?

**Comment by andrewtnisbet** [comment]
Few changes that need to be made to get this to work 

1:   the Instruments model needs an associative id to manage the connection to Musician, otherwise there is now way to build the has_many association 

The Musician migration should look like this 

```ruby 
class CreateInstruments < ActiveRecord::Migration
  def change
    create_table :instruments do |t|
      t.string :name
      t.string :type
      t.text :description
      t.integer :musician_id 

      t.timestamps null: false
    end
  end
end
```

2)  I am pretty sure that the way the validation method(has_instrument) is written, will actually look for a member variable named instruments instead of the association.  something like this is better
```ruby
   validates :instruments, :presence => true
```

3)  The Factory has a post build step for adding the instrument association 
 ```ruby 
         after :build do |musician, evaluator|
                evaluator.instrument_count.times do
                   musician.instruments << build(:instrument)
             end
      end
```
   but the test itself is calling the create command.  Build creates the object in memory, but doesn't persist it(when the validations are enforced),  Create on the other hand actually persists the model in the test DB, and enforces the validations.  a better solution would be to call the build explicitly followed by a save(the factory also need to be updated to include the musician association

Factory
```ruby
FactoryGirl.define do

  factory :musician do
    ignore do
      instrument_count 1
    end

    after :build do |musician, evaluator|
      evaluator.instrument_count.times do
        #inst = FactoryGirl.create(:instrument, musician_id: musician.id )
        musician.instruments << build(:instrument,musician_id: musician.id)

      end
    end
  end



end
```  

Musician Spec
``` ruby
require 'rails_helper'

RSpec.describe Musician, type: :model do

  describe "Musician creation" do

    it "should build a new musician" do
         @squirrelgator_mu = FactoryGirl.build(:musician)
         @squirrelgator_mu.save
    end
  end
end
```

**Comment by reconstructions** [comment]
I spent a lot of time trying to test associations (a fairly basic feature of most models) using FactoryGirl callbacks, but since I never really found clear examples which worked in practice, I finally used another approach, which has worked with all the kinds of associations I have encountered.  

It seems simpler to me and works with all the basic Rails association types.  For all I know, it has fatal flaws, or is bad practice in some way, but in case it is useful to someone who ends up stuck like I was, I will share.

First of all, I will only include associations or properties which are required to pass validations, all other associations I build in my specs' before blocks.  Second, I use nested factories to build the associations, so that I can either make 1) a simple object that will not pass validation or 2) a fully associated built object that will pass validation when saved, depending on what I need for a specific test.  This did away with the 'stack level too deep' errors that I would keep encountering when trying to troubleshoot complex associations built using callbacks.

Here’s is an example of some has_many :through factories:
```ruby
  # Musician has_many Instruments :through MusiciansInstrument
  factory :musician do
    factory :musician_with_assoc do
      # Musician must have exactly one User
      user
      # Musician must have one or many instruments
      musicians_instruments {[FactoryGirl.build(:musicians_instrument_with_instrument)]}
    end
  end

  # MusiciansInstrument belongs_to Instruments and Musicians
  factory :musicians_instrument do
    # MusiciansInstrument must have began_playing
    began_playing Time.now - 10.years
    # Musician must have at least one Instrument
    factory :musicians_instrument_with_instrument do
      instrument
    end
  end

  # Instrument has_many Musicians :through MusiciansInstrument
  factory :instrument do
    # Instrument must have an instrument_name
    instrument_name "Triangle"
  end

  # MusiciansBandsMembership belongs_to Musician, Band
  factory :musicians_bands_membership do
    # MusiciansBandsMembership must have one Musician
    factory :musicians_bands_membership_with_musician do
      musician {FactoryGirl.build(:musician_with_assoc)}
    end
  end

  # Band has_many Musicians :through MusiciansBandsMembership
  # Band has_many Genres
  factory :band do
    # Band must have a band_name
    band_name "Metallica"
    # Band must have a BandsMusiciansMembership
    factory :band_with_assoc do
      # MusiciansBandsMembership must have one or many Musicians
      musicians_bands_memberships {[FactoryGirl.build(:musicians_bands_membership_with_musician)]}
    end
  end
```
I find that this approach is very flexible, because it allow me to build all different kinds of associated models either where all the associations required by validations already exist, or in a partial form which allows me to test code that builds the associations.  It sure uses fewer lines of code than callbacks.

This gives me built associations, in case I need something which hasn't been persisted to the DB for some reason, and perhaps that speeds up my tests a little when I don't need persistence, but all I have to do is call save if that is what I want, because all the built objects will have valid associations.  I always use build in factories.rb, and usually use create in my specs.

Here are some examples of how I use these factories to build objects and attributes hashes for use in controller tests:
```ruby
    @instrument_1 = create(:instrument, instrument_name: "Bass Guitar")
    @instrument_2 = create(:instrument, instrument_name: "Drums")
    
    @musicians_instrument_1 = create(:musicians_instrument, 
      began_playing: Time.now - 15.years,
      instrument_id: @instrument_1.id)
    @musicians_instrument_2 = create(:musicians_instrument, 
      began_playing: Time.now - 25.years,
      instrument_id: @instrument_2.id)
    
    @valid_attributes = attributes_for(:musician).merge(
      :musicians_instruments_attributes => {
        "0" => attributes_for(
          :musicians_instrument,
            :began_playing => "10",
            :instrument_id => @instrument_1.id.to_s,
            :_destroy => "false"),
        "1" => attributes_for(
          :musicians_instrument,
            :began_playing => "20",
            :instrument_id => @instrument_2.id.to_s,
            :_destroy => "false") })
```
And some of the model code:
```ruby
class Musician < ActiveRecord::Base
  has_many :musicians_bands_memberships
  has_many :bands, through: :musicians_bands_memberships

  has_many :musicians_instruments
  has_many :instruments, through: :musicians_instruments
end

class MusiciansInstrument < ActiveRecord::Base
  belongs_to :musician
  belongs_to :instrument
end

class Instrument < ActiveRecord::Base
  has_many :musicians_instruments
  has_many :musicians, through: :musicians_instruments
end

class MusiciansBandsMembership < ActiveRecord::Base
  belongs_to :band
  belongs_to :musician
end

class Band < ActiveRecord::Base
  has_many :musicians_bands_memberships
  has_many :musicians, through: :musicians_bands_memberships
end
```

I have no idea whether this is really a good idea, but in the absence of really comprehensive documentation of this problem, some spirited discussions would probably help others like myself get over the hump with FactoryGirl associations.

Clean, simple, maintainable, readable, extensible, and requires 0 maintenance.
