### ISSUE TITLE
Rails 4.0.1 deprecation warnings.

### ISSUE THREAD

**Issue by Senjai** [thoughtbot/factory_girl#616]
Using the latest version of factory girl and Factory Girl Rails I get these deprecation warnings:

```
DEPRECATION WARNING: This dynamic method is deprecated. Please use e.g. Post.find_or_create_by(name: 'foo') instead. (called from block (4 levels) in <top (required)> at [FILTERED]/spec/factories/users.rb:11)
```
This is the factory:

```ruby
FactoryGirl.define do
  factory :user do
    email { Faker::Internet.email }
    password 'test1234'
    password_confirmation 'test1234'
    name "Some dude"
    factory :admin do
      after :create do |u|
        u.add_role :admin
      end
    end
  end
end
```

Nothing urgent, just thought I'd offer the heads up.

Line 11 is u.add_role :admin

**Comment by unimatrixZxero** [comment]
I'm still seeing this with factory_girl v. 4.5.0. Anybody look into where this is happening exactly yet?

**Comment by joshuaclayton** [comment]
@Senjai @unimatrixZxero FactoryGirl doesn't explicitly do `Model.find` or anything similar, apart from whatever underlying AR lookups would occur for associations. I'm closing this for now, but if there are still deprecation warnings (none show up in the FG test suite) that are reproducible, please re-open.

**Comment by unimatrixZxero** [comment]
@joshuaclayton Thanks for following up. Will do.
