### ISSUE TITLE
Using FactoryGirl for generating defaults for a model

### ISSUE THREAD

**Issue by kylemacey** [thoughtbot/factory_girl#617]
I'm thinking about developing an abstraction for setting up defaults for models supported by FactoryGirl. I wanted the defaults to be generated when called explicitly, and it may be best if I just illustrate the proposed syntax:

```ruby
User.default.new(name: "Bob")
User.default.create!
```

Where `default` would patch in default values using FactoryGirl's DSL. I would think about extending the FactoryGirl class and renaming it to avoid confusion with someone's already-defined Factories for their test suite.

Essentially, methods like `#new`, `#build`, or `#create` would super back up to the patched class, but not after being passed through FactoryGirl's `#build` or `#create` method.

Ultimately, this gives developers a familiar DSL for solving a common problem, along with flexibility such as codified attributes and defined associations.

**So** what this all boils down to is if anyone on team @thoughtbot or any other contributors see an issue with using FactoryGirl in this way, or have any reason that it shouldn't be used like this. Or maybe I could get some guidance on some gotchas to look out for or some certain areas.

Thanks for your time.

**Comment by joshuaclayton** [comment]
@kylemacey yes, https://github.com/thoughtbot/factory_girl/pull/468 and https://robots.thoughtbot.com/factory_girl-for-seed-data cover thoughts on why to avoid this.
