### ISSUE TITLE
Minitest 5?

### ISSUE THREAD

**Issue by josemotanet** [thoughtbot/factory_girl#625]
Hello everyone, I just installed Factory Girl but notice that it requires Active Support 3. Is this still necessary or can it be upgraded? It requires Minitest 4.2~ but I'd like to use version 5.

How can this be fixed? Thank you!

**Comment by joshuaclayton** [comment]
@josemotanet AS>=3 is still appropriate for FG4.x. I expect FG5 will drop support for anything pre-Rails 5 from both a gem and Ruby version perspective. You should be able to `bundle update` in the appropriate places and get this to work; let me know if you run into issues.

**Comment by josemotanet** [comment]
Thanks, Josh! :+1:
