### ISSUE TITLE
Generated factories in Rails Engine incorrectly namespaced

### ISSUE THREAD

**Issue by bbugh** [thoughtbot/factory_girl#627]
When generating a new model in a Rails mountable Engine, the factories are not class namespaced correctly. 

This test example was created with a very plain rspec+factory_girl integration, in a project called `test_project` (based on [this guide](http://viget.com/extend/rails-engine-testing-with-rspec-capybara-and-factorygirl)).

```
» rails generate model TestModel name:string
      invoke  active_record
      create    db/migrate/20140311035106_create_test_project_test_models.rb
      create    app/models/test_project/test_model.rb
      invoke    rspec
      create      spec/models/test_project/test_model_spec.rb
      invoke      factory_girl
      create        spec/factories/test_project_test_models.rb
```

The contents of `spec/factories/test_project_test_models.rb` is:

```ruby
FactoryGirl.define do
  factory :test_project_test_model, :class => 'TestModel' do
    name "MyString"
  end
end
```

If I tried to use this factory as-is, it would fail. The line should be:

```ruby
factory :test_project_test_model, :class => 'TestProject::TestModel' do
```

It looks like something is properly telling the factory to namespace the factory itself `:test_project_test_model` but the class itself is not namespaced appropriately. I am not sure if this is something getting passed in from rspec or a quirk in FactoryGirl.

---

This seems to be related to #199 and #530 and #537. If nothing has been done yet to address those, I can look into them along with this, if a) this is a bug and b) a pull request is desired.

**Comment by drapergeek** [comment]
It looks like this bug has been resolved. I can't reproduce the issue in the newest versions of FactoryGirl. If you're still having issues please let me know.
