### ISSUE TITLE
Segmentation fault on recursive association reference

### ISSUE THREAD

**Issue by ehemsley** [thoughtbot/factory_girl#628]
Something like the following:
```
let(:model) { create(:other_model, association: model) }
```
produces a segmentation fault. This is on Ruby 2.1.1 and Rails 4.0.3. 

Output is a lot of lines that look like this:
```
/Users/evanhemsley/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/memoized_helpers.rb:199:in `block in let'
/Users/evanhemsley/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/memoized_helpers.rb:199:in `fetch'
/Users/evanhemsley/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/memoized_helpers.rb:199:in `block (2 levels) in let'

-- C level backtrace information -------------------------------------------
zsh: segmentation fault  rspec spec/controllers/admin/users_controller_spec.rb
```

This is clearly not a correct usage of FactoryGirl, but I think there should be saner failure behavior than a segfault here.

**Comment by olivierlacan** [comment]
Same story in Ruby 2.2.0. 

Repro code for me:

```ruby
FactoryGirl.define do
  factory :article_subscription do
    article 
    user
  end
end
```

```ruby
  let!(:article_subscription) { create(:article_subscription, article: article) }
```

**Comment by sgrif** [comment]
You should open a bug with ruby/ruby. It should not be possible to cause a segmentation fault through plain ruby code.

**Comment by joshuaclayton** [comment]
@ehemsley @olivierlacan to confirm, this is something you can also reproduce without using Factory Girl and instead operating solely within ActiveRecord (or whatever ORM/ODM you're using), correct?

There are also a number of other areas *also* not preventing a segfault which seem much more like their responsibility (in this case, both the testing framework and ActiveRecord). I don't want to say it in a manner that comes off as "it's not my job", but rather, it's strange that this is even possible.

If it is in fact only reproducible with Factory Girl, any help to nail it down, ballpark-wise, would be helpful. We already attempt to handle self-referential attributes here: https://github.com/thoughtbot/factory_girl/blob/7e2bed5938be2e1314a7df6a647031a47d01c2c8/lib/factory_girl/attribute_list.rb#L57

**Comment by sgrif** [comment]
Even if it is only reproducible in Factory Girl, a segfault is never a library bug, it's a language bug.

**Comment by olivierlacan** [comment]
Thanks for the pointers and I agree with @sgrif but first I want to narrow down what's causing it so thanks for that @joshuaclayton. :-)

**Comment by olivierlacan** [comment]
I narrowed down the segfault inside of the RSpec's `let!` method. An infinite loop happens and I'm pretty sure this is what causes the segfault.

**Comment by olivierlacan** [comment]
@sgrif @joshuaclayton Thanks to https://github.com/rspec/rspec-core/issues/1787#issuecomment-63564263 I found the Ruby issue for this: https://bugs.ruby-lang.org/issues/9505

You should probably close this issue. :-)
