### ISSUE TITLE
Callback definitions are repetitive

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/factory_girl#640]
Consider the following factory definition:

``` ruby
  factory :reservation do
    after(:stub) do |reservation, evaluator|
      if reservation.price_cents > 0
        build_stubbed(:payment, reservation: reservation)
      end
    end

    after(:create) do |reservation, evaluator|
      if reservation.price_cents > 0
        create(:payment, reservation: reservation)
      end
    end
  end
```

The only difference between the two callbacks is the strategy used to build the payment yet I had to duplicate a bunch of code to achieve that. I have this problem often - namely I want the same exact callback for several strategies but I want the code in the callback to use the same build strategy that triggered the callback.

It'd be great if the evaluator exposed the strategy used. Something like:

```ruby
  after(:create, :stub) |reservation, |evaluator|
    if reservation.price_cents > 0
      evaluator.build_strategy(:payment, reservation: reservation)
    end
  end
```

`Evaluator` has an (private) instance variable which gets you an *instance* of the strategy. But we'd need to get from that to the name of the method to send in order to repeat that strategy on another object. If that makes sense.

**Comment by sgleadow** [comment]
I'd find this really useful as well, particularly for use with `has_many` associations and using `build_list` or `build_stubbed_list` in a single `after(:build, :stub)`, rather than having two separate hooks where the only difference is the build strategy.

**Comment by michaeldawson** [comment]
+1

**Comment by joshuaclayton** [comment]
Closing this in favor of https://github.com/thoughtbot/factory_girl/issues/458
