### ISSUE TITLE
multiple factory directories

### ISSUE THREAD

**Issue by jcavalieri** [thoughtbot/factory_girl#673]
Sorry if this documented somewhere, I couldn't find it if it is. I'm wondering if multiple directories can be passed into factory girl.

Instead of just one, e.g.
    g.fixture_replacement :factory_girl, :dir => 'test/factories'

Thanks,
John

**Comment by drapergeek** [comment]
Yes they can! That is actually the default when using `factory_girl_rails`: https://github.com/thoughtbot/factory_girl_rails#configuration

**Comment by drapergeek** [comment]
@jcavalieri I don't think that would work. This is for the generators so it is asking where you want it to create those files. If you have two directories at the top, the application wouldn't have any way of knowing which directory to put things in given a specific scenario.

**Comment by jcavalieri** [comment]
Ahh that makes sense. Thanks.

**Comment by Nowaker** [comment]
For those who found this in Google. Here's how to get multiple directories: https://github.com/thoughtbot/factory_girl/wiki/Installation
