### ISSUE TITLE
How best to use with rspec controller tests

### ISSUE THREAD

**Issue by dankohn** [thoughtbot/factory_girl#676]
I'm using scaffolding to generate rspec controller tests. By default, it creates the test as:

```ruby
let(:valid_attributes) {
  skip("Add a hash of attributes valid for your model")
}

describe "PUT update" do
  describe "with valid params" do
    let(:new_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    it "updates the requested doctor" do
      company = Company.create! valid_attributes
      put :update, {:id => company.to_param, :company => new_attributes}, valid_session
      company.reload
      skip("Add assertions for updated state")
    end
```

Using FactoryGirl, I've filled this in with:

```ruby
let(:valid_attributes) { FactoryGirl.build(:company).attributes.symbolize_keys }

describe "PUT update" do
  describe "with valid params" do
    let(:new_attributes) { FactoryGirl.build(:company, name: 'New Name').attributes.symbolize_keys }

    it "updates the requested company", focus: true do
      company = Company.create! valid_attributes
      put :update, {:id => company.to_param, :company => new_attributes}, valid_session
      company.reload
      expect(assigns(:company).attributes.symbolize_keys[:name]).to eq(new_attributes[:name])
```

This works, but it seems like I should be able to test all attributes, instead of just testing the changed name. I tried changing the last line to:

```ruby
class Hash
  def delete_mutable_attributes
    self.delete_if { |k, v| %w[id created_at updated_at].member?(k) }
  end
end

expect(assigns(:company).attributes.delete_mutable_attributes.symbolize_keys).to eq(new_attributes)
```

That almost worked, but I'm getting the following error from rspec having to do with BigDecimal fields:

```ruby
-:latitude => #<BigDecimal:7fe376b430c8,'0.8137713195 830835E2',27(27)>,
-:longitude => #<BigDecimal:7fe376b43078,'-0.1270954650 1027958E3',27(27)>,
+:latitude => #<BigDecimal:7fe3767eadb8,'0.8137713195 830835E2',27(27)>,
+:longitude => #<BigDecimal:7fe3767ead40,'-0.1270954650 1027958E3',27(27)>,
```

Note that my factory looks like:

```ruby
latitude { Faker::Address.latitude }
longitude { Faker::Address.longitude }
```

So my questions are:

What is a good example of an rspec and factory_girl test for a PUT update with valid params?
Is it necessary to use `attributes.symbolize_keys` and to delete the mutable keys? How can I get those BigDecimal objects to evaluate as `eq`?

I've reviewed past discussions about [attributes_for should honor associations defined in the factory](https://github.com/thoughtbot/factory_girl/issues/359). Would you be interested in accepting a pull request for a `non_mutable_keys` method that would return attributes ready to be compared by rspec, including support for associations?

@joshuaclayton, I noted you [saying](https://github.com/thoughtbot/factory_girl/issues/359#issuecomment-10954639) that you didn't want to support Rails-specific features. I wonder if you would consider accepting a pull request for this kind of method into https://github.com/thoughtbot/factory_girl_rails instead?

Finally, my apologies for asking such a large question, but I wanted to point out that using rspec, factory_girl, and scaffolding is incredibly common, and nearly everyone who does so will wind up searching through all of these issues like I have.

**Comment by drapergeek** [comment]
Hi @dankohn I'll try to provide a bit of help.

First, is there a reason you're preferring the `attributes.symbolize_keys` over using the `attributes_for` method?

As for validating the updated_attributes, I'm not sure that factory_girl makes sense here. Specifically you should be passing in the new_attributes and verifying those. Here is something I tossed to together as an example of how I might approach this.

```ruby
      let(:new_attributes) {
        { name: "Superman" }
      }

      it "updates the requested superhero" do
        superhero = Superhero.create! valid_attributes
        put :update, {:id => superhero.to_param, :superhero => new_attributes}, valid_session
        superhero.reload
        new_attributes.each_pair do |key, value|
          expect(superhero[key]).to eq(value)
        end
      end
```

The reason I recommend using just a hash instead of the factory girl attributes is that you want to know what attributes you're actually overriding vs the ones that are the same as in your `valid_attributes` method.

I'm sure this doesn't completely answer your question but maybe it can get the discussion moving forward!

**Comment by dankohn** [comment]
@drapergeek thanks for the reply. I provided much more info on my journey down the rabbit hole in this StackOverflow question and answer: http://stackoverflow.com/a/24986965/1935918

I do like your solution of iterating through the `new_attributes` rather than looking at all keys of `superhero`. That avoids the issue of mutable keys, and would probably work even if you did `let(:new_attributes) { FactoryGirl.attributes_for(:superhero, name: 'Superman') }`.

I ultimately decided, however, that checking all keys was not worthwhile, as it was exposing too many strange boundary conditions around RSpec, as opposed to testing something valuable about my code.

**Comment by drapergeek** [comment]
I think that's the right solution as well!  Thanks for replying.

**Comment by nelantone** [comment]
Thanks! Very helpful for me to :)! 
Completely agree!
:+1:
