### ISSUE TITLE
Skip validation for parent factory

### ISSUE THREAD

**Issue by nicohvi** [thoughtbot/factory_girl#686]
In order to DRY up the factories for some models it might be beneficial to add the option to skip validation for the parent factory in the cases where a nested resource requires a parent resource in order to be created, but there are different kinds of parents.

Example:

````
class Article
  has_many :comments
end

class Image
  has_many :comments
end

class Comment
  belongs_to :article
  belongs_to :image

  validates :article_or_image

  private

  # ensure the comment only belongs to *one* parent resource
  def article_or_image
    if !(article.nil? ^ image.nil?)
      errors.add(:base, 'A comment must belong to either an article or an image.')
    end
  end
end
`````

Now in my test suite, I might want to do something like this

````
factory :comment do
  name 'Commenter'
  body 'This is a glorious comment.'
  
  factory :article_comment do
    article
  end

  factory :image_comment do
    image
  end

end
````

But this will raise an `InvalidFactory` error since the `comment` factory does not pass `valid?`. Any thoughs on this?

**Comment by nysthee** [comment]
Isn't this something you could do with traits? http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Traits

**Comment by joshuaclayton** [comment]
@nicohvi traits would definitely work like @nysthee mentioned:

```ruby
trait :base_comment do
  name "Commenter"
  body "This is a glorious comment."
end

factory :article_comment, class: Comment, traits: [:base_comment] do
  article
end

factory :image_comment, class: Comment, traits: [:base_comment] do
  image
end
```
