### ISSUE TITLE
attributes_for not building belongs_to association

### ISSUE THREAD

**Issue by waaadim** [thoughtbot/factory_girl#687]
factory :post do
  association :author, factory: :user, last_name: "Writely"
end

so the thing is that "author" is nil when doing attributes_for(:post). I don't know if this is the expected result or not. I expected it to return an id in this situation.

as a workaround I'm building the the post "post = build(:post)" then I'm doing post.attributes. which is not nice

**Comment by joshuaclayton** [comment]
@waaadim it is the expected result - for `attributes_for`, we don't create any association data: https://github.com/thoughtbot/factory_girl/blob/4a4a0b90f278f48298ef97a12425e1a120cb8abd/lib/factory_girl/strategy/attributes_for.rb#L4-L6

Your approach should work in cases like `accepts_nested_attributes_for`.

**Comment by rlue** [comment]
Is there any way to override this behavior? I have a factory with an attribute that depends on an association:

```
FactoryGirl.define do
  factory :order do
    supplier
    purchaser
    sequence(:invoice) { |n| "#{purchaser.code}-#{sprintf('%04d', n)}" }
  end
end
```

and this behavior is causing `::attributes_for` to fail:

```
>> FactoryGirl.attributes_for(:order)
NoMethodError: undefined method `code' for nil:NilClass
```

In this particular case, I imagine I could use `accepts_nested_attributes_for` as a workaround, but what if I had a factory attribute that depended on multiple associations?

Is there a reason for this particular design choice?
