### ISSUE TITLE
Non-association attributes ignore passed in values on `FactoryGirl::create`

### ISSUE THREAD

**Issue by brittlewis12** [thoughtbot/factory_girl#688]
I'm working with an object that has both `service_type` and `service_type_id` attributes (no association at all, it's from a third party system), and the Factory nils out the non-id attribute each time I try to set both by passing a hash to `.create`:
```ruby
FactoryGirl.create(:service, service_type: 'help', service_type_id: 105)
# => #<Service id: 1, service_type: nil, service_type_id: 105>
```

When both attributes are defined inside a `FactoryGirl.define` block, when **no hash** is passed in to `.create`, the factory object has both attributes:
```ruby
FactoryGirl.define do
  factory :service do
    service_type { 'default service' }
    service_type_id { 10 }
  end
end

FactoryGirl.create(:service)
# => #<Service id: 1, service_type: 'default service', service_type_id: 10>
```

However, even with both defined in the Factory, attempting to override both values with a hash results in the same behavior as described above.

So far, the only work around is to assign the non-id attribute a value in an after block. This works, but of course I'd like to be able to assign values in the hash passed to `.create`. Does FactoryGirl assume attributes that differ only by '_id' at the end are meant to both reference an association? Might it be more desirable to require explicitly calling out an association as such to achieve this behavior?

(Admittedly, this may be a factory_girl_rails issue, as I'm using v4.2.0 with factory_girl_rails v4.2.1 and Rails 4.0, so I've cross-posted this there as well.)

**Comment by shyam-habarakada** [comment]
I have the same problem. I am able to assign one, but not both `service` or `service_id` via a hash during create. Trying to assign both during create results in both values being set as `nil`

**Comment by shyam-habarakada** [comment]
@joshuaclayton can you please comment on this? The usage seems correct, but FactoryGirl is not behaving as one would expect. Is this a bug?

**Comment by joshuaclayton** [comment]
@shyam-habarakada this is actually an intended aspect of FG, due to how AR inherently treats associations and foreign keys. I discuss this more in-depth [here](https://github.com/thoughtbot/factory_girl/issues/522#issuecomment-17480267). My recommendation would be to avoid using `#{attr}` and `#{attr}_id`; if possible, I'd create a mapping so the external system can get at the appropriate data, but have internal tooling around the method(s) here to ensure they're not being treated as FKs.
