### ISSUE TITLE
Accessing attributes from initialize_with when duplicate assignment is enabled is deprecated

### ISSUE THREAD

**Issue by amejiarosario** [thoughtbot/factory_girl#690]
I have the following setup to generate JSON messages. It's working perfectly!  The only problem I'm getting is an anoying deprecation warning:

**DEPRECATION WARNING: Accessing attributes from initialize_with when duplicate assignment is enabled is deprecated; use FactoryGirl.duplicate_attribute_assignment_from_initialize_with = false. (called from block (5 levels) in <top (required)> at /mnt/hgfs/..._spec.rb:43)**

This is my factory:
```ruby
FactoryGirl.define do
  factory :internaluser_job, class: 'Object' do
    skip_create

    ignore do
      schema_id 1
      source nil
      internaluser nil
      type 'create'
    end

    initialize_with do
      {
        schema_id: schema_id,
        source: source,
        type: type,
        data: {
          internaluser: create(:internaluser, internaluser).attributes
        }
      }.to_json
    end
  end
end
```

And in my test I'm calling it as follows:

```ruby
FactoryGirl.create(
  :internaluser_job,
  type: 'create',
  internaluser: {
    cleanup_time: 7,
    never_expire: false
  }
)
```

I'm using factory_girl-3.5.0 and rspec-core-2.10.1... Any ideas how do I avoid the warning?

**Comment by joshuaclayton** [comment]
You can call `FactoryGirl.duplicate_attribute_assignment_from_initialize_with = false` in your RSpec config to address this.

**Comment by amejiarosario** [comment]
No more ruby for me. I moved to the JavaScript world couple of years ago :)
