### ISSUE TITLE
Suggestion:  Add error messages to FactoryGirl.lint output

### ISSUE THREAD

**Issue by jwhitmire** [thoughtbot/factory_girl#691]
When you get a lint failure, it would be very helpful to have it dump the error messages from the failing factory so you can easily see and fix the issue.  Seeing the invalid factories is good but then you have to go recreate the issue in console to find out why the factory is not valid in its default state.

I have a proposed solution working on a branch that I'll attach to this issue.

**Comment by shirshendu** [comment]
The attached fix does indeed resolve this issue. @joshuaclayton might want to look into closing this.
