### ISSUE TITLE
Where do you place modified factories?

### ISSUE THREAD

**Issue by BenMorganIO** [thoughtbot/factory_girl#701]
Hey there,

Just wondering if the readme can be updating on specifying where one would best place decorated factories.

Quite often, I get the `Factory not registered` error. I often just place them in a `factory_decorators` folder outside of `factories`, but I don't feel this is the rails way.

Thoughts?

**Comment by drapergeek** [comment]
@BenMorganIO This is a personal decision. At thoughtbot we only have a single file for factories to keep things simple. If the file grew to a size that we felt the need to break it up, I think how it was broken up would be an individual decision based on the type of project.

Sorry there isn't an easy answer on this one!
