### ISSUE TITLE
"include FactoryGirl::Syntax::Methods" doesn't work in test_data block (Test::Unit)

### ISSUE THREAD

**Issue by BartlomiejSkwira** [thoughtbot/factory_girl#706]
```ruby
#test_helper.rb
class Test::Unit::TestCase
  include FactoryGirl::Syntax::Methods
end

#some_controller_test.rb
require 'test_helper'

class SomeControllerTest < ActionController::TestCase
  test_data do
    create(:model)  #EXCEPTION
#=> NoMethodError: undefined method `create' for SomeControllerTest:Class
  end

 
  setup do
    create(:model) #WORKS
  end
end
```
So the short syntax methods don't work i `test_data` blocks for some reason, even if I `include` just before create.

**Comment by artptr** [comment]
History of lib/factory_girl/syntax/methods.rb shows that all methods was removed by commits c8c1a801ed22ae3695db7d2f29b2d8ff47971b9d and 95a4626daad3ec6e6833f48fb07ec9becaa13bd5. Maybe there is a new mechanism of dynamic loading of such methods, but it isn't described in the docs.

**Comment by joshuaclayton** [comment]
@artptr in those commits, we move to calling `module_exec` on `FactoryGirl::Syntax::Methods` to define them dynamically, so that shouldn't be the issue.

@BartlomiejSkwira does `test_data` yield an instance of `Test::Unit::TestCase`? If not, including in `Test::Unit::TestCase` won't work correctly.

**Comment by joshuaclayton** [comment]
Closed ude to inactivity; feel free to re-open if the issue still exists.
