### ISSUE TITLE
build_stubbed support for UUID

### ISSUE THREAD

**Issue by allaire** [thoughtbot/factory_girl#713]
Getting the following error:

```
ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: uuid <> integer
        LINE 1: ...rs"."email" = 'buford@erdman.ca' AND "users"."id" != 1002) L...
```

I'm using UUID for my keys, and `build_stubbed` tries to create my relationship using an integer instead of a uuid.

Anyway to have a setting to decide between an id and a uuid?

`build` and `create` work well because they persist on the database the relationships.

Thanks!

**Comment by jerry-tao** [comment]
Same issus, here is the details.
When validate with the unique it will look up the database. So the 1xxx id is wrong.

Here is my quick fix.

```
require 'factory_girl_rails'

module FactoryGirl
  module Strategy
    class Stub
      private
      def next_id
        SecureRandom.uuid
      end
    end
  end
end
```

I'm not very good at ruby. So just leave the message here. Hope next version could fix it.

**Comment by fourseven** [comment]
Thank you @jerry-tao, that snippet worked perfectly, I/we just ran into the same issue.

**Comment by whatthewhat** [comment]
Are there any plans to support UUIDs? I'd be up to work on a PR for this.

**Comment by andyw8** [comment]
Just ran into this too. Thanks for the workaround @jerry-tao.

**Comment by joshuaclayton** [comment]
I'd welcome a PR that provides FG configuration for a class whose responsibility is to generate the next id for `build_stubbed`. Closing this for now.

**Comment by valer-cara** [comment]
I've tried out the following, to keep the change at a factory level. I think the suggested monkeypatch above changes all factories, right?

```
after(:build_stubbed) do |record|
  record.id = SecureRandom.uuid
end
```

**Comment by scifisamurai** [comment]
I ran into this today.  Just wanted to mention that the workaround provided by @valer-cara above does work as long as you use `after(:stub)`  instead of `after(:build_stubbed)` since `after(:stub)` is the appropriate callback to use when using `build_stubbed` as per https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#callbacks
