### ISSUE TITLE
FactoryGirl.lint not respecting webmock configuration

### ISSUE THREAD

**Issue by shedd** [thoughtbot/factory_girl#714]
I have an after_create call on a model that makes an HTTP request to an external service.  Even though I've stubbed this in an RSpec config(:before) block (just like you show here!  http://robots.thoughtbot.com/how-to-stub-external-services-in-tests) I'm still getting webmock failures when FactoryGirl.lint runs.

If I remove my call to FactoryGirl.lint, everything works fine.

So FactoryGirl.lint seems to not be loading the full set of RSpec configure sequences?

This is with 4.5.0.  I didn't have this problem on 4.4.0 - only saw it after upgrading.

**Comment by joshpfosi** [comment]
I was having this same issue and I this should resolve it. One recommendation is if you are using `DatabaseCleaner` before your suite,  using `DatabaseCleaner.start` within a spec will issue a warning.

```ruby
RSpec.describe FactoryGirl do
  it 'lints factories successfully' do
    described_class.lint
  end
end
```

works well for me!
