### ISSUE TITLE
what about class variables?

### ISSUE THREAD

**Issue by lumpidu** [thoughtbot/factory_girl#715]
Have googled around but haven't found any hints:
Is there a way to define class variables with factory girl?

**Comment by joshuaclayton** [comment]
@lumpidu https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#custom-construction might be a good place to start.

Please be aware that mutable class attributes can cause loads of problems when running tests in parallel, and in general is tricky to ensure there's no "state bleed" between tests.
