### ISSUE TITLE
Rspec not cleaning factories after upgrade.

### ISSUE THREAD

**Issue by juniorjp** [thoughtbot/factory_girl#716]
Hi,

I upgraded factory_girl and factory_girl_rails to 4.5.0 and my tests stop working. It is throwing "Invalid record" and it seems the database is not getting cleaned after each test.

```
gem 'factory_girl_rails', '~> 4.5'
```
If I rollback versions to:

```
gem 'factory_girl_rails', '4.4.0'
gem 'factory_girl_rails', '4.4.1'
```

The tests work fine again. Any changes that could break the tests like this?

**Comment by drapergeek** [comment]
I believe that @alext is probably right. We've added documentation to specify that you'll want to run a DB cleaner after running the linter: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#linting-factories
