### ISSUE TITLE
README.md is unreadable when access from "GETTING STARTED"

### ISSUE THREAD

**Issue by ldonnet** [thoughtbot/factory_girl#727]
When I access ["GETTING STARTED"](http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md) link from main page it fails.
![file getting_started documentation for factory_girl 4 5 0](https://cloud.githubusercontent.com/assets/314537/5359243/168657a8-7fbc-11e4-9998-eea09399413c.png)

**Comment by allcentury** [comment]
This is due to a browser extension such as Markdown Preview, it renders fine if you turn it off.

**Comment by ldonnet** [comment]
Hi you are right! Thanks for your help!
