### ISSUE TITLE
FactoryGirl association not allowing multiple traits input

### ISSUE THREAD

**Issue by boyfunky** [thoughtbot/factory_girl#728]
I have three factories file namely interest_rate_reference.rb, banks.rb and mortgage_loans.rb

All files have about 3-4 traits in each file.

the mortgage_loans.rb file is as follows

FactoryGirl.define do 
  factory :mortgage_loan do

    trait :legacy_id_266 do
      legacy_id 266
      bank_id 1
      name "Maxi Home"
      loan_purpose "both"
      is_conventional 1
      is_islamic 0
      minimum_tenure 5
      maximum_tenure 35
      minimum_amount 300000 
      maximum_amount 999999999
      interest_rate_type "float"
      interest_rate_percentage 2.40
      is_flexi 0
      completion_status "both"
      maximum_finance 90
      notes ""
      land_type "residential"
      interest_rate_reference_id 6
      is_add_interest_rate 0
      effective_rate 4.45
      lock_in_period 3
      penalty "2%"
      is_featured 0  
    end

    trait :legacy_id_260 do
      legacy_id 260
      bank_id 1
      name "Maxi Home"
      loan_purpose "both"
      is_conventional 1
      is_islamic 0
      minimum_tenure 5
      maximum_tenure 30
      minimum_amount 300000 
      maximum_amount 999999999
      interest_rate_type "float"
      interest_rate_percentage 2.40
      is_flexi 0
      completion_status "both"
      maximum_finance 90
      notes ""
      land_type "residential"
      interest_rate_reference_id 6
      is_add_interest_rate 0
      effective_rate 4.45
      lock_in_period 3
      penalty "2%"
      is_featured 0  
    end

    trait :legacy_id_261 do
      legacy_id 261
      bank_id 1
      name "Maxi Home -i"
      loan_purpose "both"
      is_conventional 1
      is_islamic 0
      minimum_tenure 5
      maximum_tenure 35
      minimum_amount 300000 
      maximum_amount 999999999
      interest_rate_type "float"
      interest_rate_percentage 2.40
      is_flexi 0
      completion_status "both"
      maximum_finance 80
      notes ""
      land_type "residential"
      interest_rate_reference_id 7
      is_add_interest_rate 0
      effective_rate 4.45
      lock_in_period 3
      penalty "2%"
      is_featured 0  
    end

    trait :legacy_id_262 do
      legacy_id 262
      bank_id 2
      name "CIMB Flexi"
      loan_purpose "both"
      is_conventional 1
      is_islamic 0
      minimum_tenure 5
      maximum_tenure 35
      minimum_amount 300000 
      maximum_amount 999999999
      interest_rate_type "float"
      interest_rate_percentage 2.40
      is_flexi 0
      completion_status "both"
      maximum_finance 90
      notes ""
      land_type "residential"
      interest_rate_reference_id 7
      is_add_interest_rate 0
      effective_rate 4.45
      lock_in_period 3
      penalty "2%"
      is_featured 0  
    end

    association :interest_rate_reference, :factory=> [:interest_rate_reference, :blr]
    association :interest_rate_reference, :factory=> [:interest_rate_reference, :mlr]
    association :bank, :factory=> [:bank, :maybank]
    association :bank, :factory=> [:bank, :cimb]
  end
end`

In my mortgage_loans_spec.rb

scenario "Test Database using Update Result" do
    build(:mortgage_loan, :legacy_id_266)
    build(:mortgage_loan, :legacy_id_260)
    build(:mortgage_loan, :legacy_id_262)
    build(:mortgage_loan, :legacy_id_261)
    click_button("Update Results")
  end 

When i run this code, it gives error

Failure/Error: build(:mortgage_loan, :legacy_id_266)
     FactoryGirl::AttributeDefinitionError:
       Attribute already defined: interest_rate_reference

Does anyone know why and and is there a better way to rewrite or refactor this code. The result should give 4 rows because they fit the condition set to display when the button is clicked.

Thanks

**Comment by drapergeek** [comment]
@boyfunky I'm not sure exactly what you're trying to reproduce but your primary problem is here:

```
association :interest_rate_reference, :factory=> [:interest_rate_reference, :blr]
association :interest_rate_reference, :factory=> [:interest_rate_reference, :mlr]
```

You're trying to define the `intererest_rate_reference` in two different ways on the same factory. If you want to perform differently in different scenarios, you would to put that on the individual trait, rather than at the factory level.

The same would apply to the bank association.

I hope this helps, if not, feel free to respond and I'll see if I can clarify further.
