### ISSUE TITLE
Specifying associations to inherited factory with FactoryGirl

### ISSUE THREAD

**Issue by constantm** [thoughtbot/factory_girl#730]
I've just started using FactoryGirl for my tests, and I've run into some issues. 

I have `user`, `qualification` and `user_qualification` models. For `qualifications`, I have two inherited factories, namely `qualification_ba` and `qualification_phd`. Now, I'm trying to generate a qualification that includes either `qualification_ba` or `qualification_phd` factories by running:
 
`create(:user_qualification_ba_bad_marks)`. 

This returns:

`NoMethodError: undefined method 'qualification_ba='`. 

However, when running: 

`create(:qualification_ba)` 

it successfully creates the object as expected. Is there perhaps a limit on how deep you can nest factories?
```
  	factory :user do
  		to_create {|instance| instance.save(validate: false) }

  		full_name				Faker::Name.name
  		email					Faker::Internet.email
  		password				Faker::Internet.password(8)

  	    factory :user_ba_candidate do
  			before(:create) do |user|
        			create_list(:user_qualification_ba_bad_marks, 1, user: user)
      		end
	  	end

	  	factory :user_phd_candidate do
	  		before(:create) do |user|
        			create_list(:user_qualification_phd_good_marks, 1, user: user )
      		end
	  	end

  	end
  	factory :qualification do
  		user_selectable true
  		factory :qualification_ba do
  			name 					"Bachelors"
  			qualification_level 	2
  		end
  		factory :qualification_phd do
  			name 					"Masters"
  			qualification_level 	5
  		end
  	end
  
  	factory :user_qualification do
  		to_create {|instance| instance.save(validate: false) }
  		factory :user_qualification_ba_bad_marks do
  			qualification_ba
  			aggregate (30..50).to_a.sample
  		end
  		factory :user_qualification_phd_good_marks do
  			qualification_phd
  			aggregate (70..90).to_a.sample
  		end
  		user
	end
```

**Comment by drapergeek** [comment]
I think the issue here is that factory_girl doesn't know that `qualificatino_ba` is not an actual method on the model. You can specify the association like this to allow it to know:

```
association(:qualification, factory: qualification_ba)
```

I would also recommend using traits over nested factories, it makes things easier to compose in multiple scenarios. You can read more about that here: https://robots.thoughtbot.com/remove-duplication-with-factorygirls-traits

Hope that helps!
