### ISSUE TITLE
Pass Hash with attributes

### ISSUE THREAD

**Issue by emmanuelmillionaer** [thoughtbot/factory_girl#731]
Normally i define my factories like this one:

    FactoryGirl.define do
      factory :user do
        vorname "John"
        ......
        ......
But in my recent project i get the data from a File in shape of a Hash:

     read_data_from_file('data.xml')
       => {:vorname => "John" .......}
Is it somehow possible to write my Factories like this?

    FactoryGirl.define do
      factory :user do
        {:vorname => "John"...}
      end
    end
Ps. When I tried to run my test like this It returned:

    expect(build(:user).vorname).to eq("John")

       expected: "John"
            got: nil

**Comment by romulomachado** [comment]
I'm not sure what you're trying to achieve there, but my solution would be storing the `read_data_from_file('data.xml')` output to a variable and building the factory only with the values, not the keys.

```ruby

data = read_data_from_file('data.xml')

FactoryGirl.define do
  factory :user do
    vorname data[:vorname]
  end
end
```

**Comment by drapergeek** [comment]
It may not be a great option but you can actually pass a hash to the `attributes` method:

```
  factory :user do
    attributes { {:vorname => "John"} }
  end
```

I do think that @romulomachado's  solution would be preferable to mine.
