### ISSUE TITLE
Unable to handle field named "method"

### ISSUE THREAD

**Issue by mhuggins** [thoughtbot/factory_girl#732]
I'm working with a database that implements a field named "method".  (An existing method name on `Object`, I know, but not a name I picked since it's someone else's existing project. :smile:)  In any case, I can't get FactoryGirl to assign an attribute value to this field.  I've tried:

```ruby
method 'value'
self.method 'value'
self.method = 'value'
```

All of these raise an error that kills my test suite.  The only thing that "works", though doesn't seem to properly be taken into account when using `attributes_for`, is:

```ruby
after(:build) do |instance|
  instance.method ||= 'value'
end
```

How can I make this work AND be taken into account by `attribute_for`?

**Comment by joshuaclayton** [comment]
@mhuggins `add_attribute` should do the trick:

```ruby
factory :foo do
  add_attribute(:method) { "value" }
  # or
  add_attribute(:method, "value")
end
```
