### ISSUE TITLE
belongs_to and validates :presence validations failing

### ISSUE THREAD

**Issue by benwalsh** [thoughtbot/factory_girl#735]
After upgrading from FactoryGirl 2.5.2 to 4.5.0, validations for belongs_to associations fail.

The two model files:

```
class User < ActiveRecord::Base    
  ...
  has_many :things
  ...
end

class Thing < ActiveRecord::Base
  ...
  belongs_to :user   
  validates_presence_of :user
  ...
end
```

The factory:
```
FactoryGirl.define
  factory :thing do
    association :user      
    ...
  end
end
```
Creating a new thing always fails saying `User must be provided`. When I step into the code, the foreign key is set correctly, the object exists, but the association is not recognized:

```
>> user = create(:user)
  ( returns saved "user" object )
>> user.id
1
>> thing = build(:thing, user: user)
  ( returns new "thing" object )
>> thing.valid?
false
>> thing.user_id
1
>> User.find(1).present?
true
>> thing.user
nil
```

I've tried all sorts of combinations and variations on this. I've tried using `after(:build)` blocks to set the user and using different FactoryGirl syntax. I've tried just having a plain user instead of the association. But it always comes down to this problem -- there is an associated key, and it is correct, but not an associated object (even though that object exists and is saved).

Environment:

```
ruby 2.1.5

factory_girl 4.5.0
factory_girl_rails 4.5.0
rails 4.2.0
rspec 3.1.0
```

**Comment by benwalsh** [comment]
Seems that this is not a factory_girl issue at all but a Rails 4.2 one.

**Comment by md5** [comment]
@benwalsh Any chance you remember the details of this problem? I've just started running into it myself.

**Comment by benwalsh** [comment]
@md5 [Here's where we left it last](https://github.com/rails/rails/issues/18563). We have continued on the 4.1.x path for the moment so haven't revisited in a while.

**Comment by md5** [comment]
Thanks @benwalsh

**Comment by md5** [comment]
@benwalsh Does this looks like a valid test for this problem? https://gist.github.com/md5/00a4416c3f229695a3f3

Unfortunately, it doesn't reproduce the problem I'm seeing, either with Rails `master` or with 4.2.4 (or 4.2.5).

**Comment by md5** [comment]
I tracked this down to user error in our case.

There was a factory that wasn't creating one of the required `belongs_to` associations. The spec in question was passing in an associated object as an override to `create_list`, but another code path was creating its own instance without the override and failing the validation. Since this problem probably isn't relevant to the issue you were seeing, it's not worth the time for me to extract it into a demonstrable test case.
