### ISSUE TITLE
Skip AR callbacks

### ISSUE THREAD

**Issue by zamith** [thoughtbot/factory_girl#736]
Is it possible to skip AR callbacks on the creation of a record?

**Comment by MattMSumner** [comment]
You can use `to_create` to customize how your factory gets created. See https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#custom-methods-to-persist-objects

If you pair this with http://stackoverflow.com/a/21371833/1489062 you should get what you looking for.

If you don't mind me asking, why are you trying to skip callbacks? If your skipping it in your application it might be worth considering if it really should be a callback.

**Comment by zamith** [comment]
I got around it without actually needing to skip the callback, but thanks anyway.

I'm going to close this issue.
