### ISSUE TITLE
Unable to handle after create for model named model.

### ISSUE THREAD

**Issue by bagus1** [thoughtbot/factory_girl#738]
model has_many foo

```
FactoryGirl.define do
  factory :model, class: Model do
    name 'test'
    factory :model_with_foo do
      after(:create) do |model|
       create(:foo, model: model)
      end
    end
  end

  factory :foo, class: Foo do
    model
    name 'Test Foo'
  end
end
```

Failure/Error: e = create(:model_with_foo)
     NoMethodError:
       undefined method `model=' for #<Foo:0x007fe5da8d6d38>
etc

Any way around this other than renaming the 'model' model?

**Comment by joshuaclayton** [comment]
@bagus1 have you migrated your database? FactoryGirl shouldn't have any trouble assigning an attribute named model; the problem seems to be there being no `#model=` setter on `Foo`.

**Comment by bagus1** [comment]
Yes, @joshuaclayton, the database is migrated. 

I'm pretty sure this is an issue. I have other factories doing very similar things that work just fine. 

One hint as to a problem is that in my code editor (sublime), both instances of the word 'model' in the create params are highlighted in the same color as the word 'class' in the 'factory :model, class: Model' line, whereas in my other factories, the first 'model' matches the text of the first params, and the second 'model' matches those of typical variables. So.. I don't see 'model' on lists of reserved words in ruby, but something like that does seem to be going on. 

Anyways, is there an alternate syntax? Thanks for your advice

**Comment by joshuaclayton** [comment]
@bagus1 any updates here? If so, feel free to reopen. The error you're seeing looks to be based on the ActiveRecord model not responding to the setter method, so it should be reproducible by (in a test) doing:

```ruby
foo = Foo.new
foo.model = Model.new
```

If that fails, it's not an issue with FG, but rather something else going on in the system where the setter isn't available for whatever reason.
