### ISSUE TITLE
Image file attribute is missing randomly

### ISSUE THREAD

**Issue by joker-777** [thoughtbot/factory_girl#739]
Hi guys,

we have a strange bug. Our factory looks a like this
```ruby
FactoryGirl.define do

  factory :sequence, :class => Sequence do
    new_image { File.new("#{Rails.root}/app/assets/images/fav.png") }
    old_image { File.new("#{Rails.root}/app/assets/images/fav.png") }

  end 
end
```
and our spec file looks similar to this
```ruby
  before do
    @seq = FactoryGirl.create(:sequence)
  end

  it 'test 1' do
  end

  it 'test 2' do
  end

  it 'test 3' do
  end
```
`new_image` and `old_image` are both mandatory. 'test1' and 'test2' worked fine but in 'test 3' the following error got raised
```
ActiveRecord::RecordInvalid: Validation failed: New image can't be blank
```
We put some `puts` statements in the `new_image {}` block and through this we could ensure that the image exists and that a file image object was returned. But somehow factory girl doesn't assign it to the new sequence object and then this error is raised by the model validator.

It is important to note that this error happens highly random. Maybe every fifth run and it also happens in different tests. It doesn't matter if it is a capybara test, request test or controller test. This is just an example spec where we just experienced this error again.

**Comment by andrewtnisbet** [comment]
Hi,  I am struggling to replicate your issue, and have a few questions. 
1)   Are you still seeing this problem?(I know its been a few months)
2)   What versions of Ruby, Rails, RSpec and Factory Girl are you using? 

Thanks 

Andrew

**Comment by joker-777** [comment]
Hi Andrew,

thanks for replying. We don't have this problem anymore since we changed the two attributes to use two different image files.
It would be still interesting why this sometimes happened. I understand that it is very difficult to reproduce. It was the same for us too. Wie use
Ruby 2.2.0
rspec 3.1.0
factory_girl 4.5.0

Johannes

**Comment by andrewtnisbet** [comment]
Hi,    I spent a few hours this morning trying to reproduce this issue, without much success.  Given that this does not appear to be a problem for the user any longer. I believe its safe to close this defect as unable to reproduce. It can always be reopened, if the problem manifests itself again in the future.

**Comment by joker-777** [comment]
Ok, no problem.
