### ISSUE TITLE
Invoke factory with class name instead of factory name

### ISSUE THREAD

**Issue by thermaldonkey** [thoughtbot/factory_girl#740]
I've got an ActiveRecord model and a basic factory set up for it, under the normal Rails naming convention:

```ruby
# app/models/panel.rb
class Panel < ActiveRecord::Base
  # model stuff
end

# spec/factories/panels.rb
FactoryGirl.define do
  factory :panel do
    # factory stuff
  end
end
```

I've noticed in my RSpec tests I can invoke this factory with either the factory name _or_ the model's class name:

```ruby
FactoryGirl.create(:panel)

FactoryGirl.create(Panel)
```

The latter is preferable, because it means I can replace literal symbols with RSpec's `described_class` helper.

So now, I've got another model that I'm attempting to do this for, but when invoking the factory, I see:

```ruby
ArgumentError:
  Factory not registered: ModelNamespace::OtherModel
```

I've defined the model and factory as follows:

```ruby
# app/models/model_namespace/other_model.rb
class ModelNamespace::OtherModel < ActiveRecord::Base
  # database table for model is named 'model_namespace_other_models', yay for inheriting legacy systems!
  # model stuff
end

# spec/factories/model_namespace_other_models.rb
FactoryGirl.define do
  factory(:other_model, class: ModelNamespace::OtherModel) do
    # factory stuff
  end
end
```

Is there a way I could redefine either to fix the resolution issue, or am I misusing this feature of FactoryGirl?

**Comment by ajm188** [comment]
What if you tried this?
```ruby
FactoryGirl.define do
  factory(:"ModelNamespace::OtherModel") do
    # factory stuff
  end
end

FactoryGirl.create(ModelNamespace::OtherModel)
```

**Comment by tmichel** [comment]
I hit this bug as well. For a quick workaround you can register the same (named) factory again with the class name and avoid duplication of all attributes:

```ruby
FactoryGirl.define do
  factory :panel do
    # factory stuff

    # register the same factory for the class as well
    factory(Panel)
  end
end
```

**Comment by joshuaclayton** [comment]
This was an unintended effect and has been deprecated: https://github.com/thoughtbot/factory_girl/pull/843

In FG5, only accessing via symbol will work.
