### ISSUE TITLE
Documentation Request: Sequence Definition

### ISSUE THREAD

**Issue by jaredbeck** [thoughtbot/factory_girl#741]
[GETTING_STARTED.md][1] says:

> Sequences can be used as attributes:
> 
>     factory :user do
>       email
>     end
> 
> Or in lazy attributes:
> 
>     factory :invite do
>       invitee { generate(:email) }
>     end

Please clarify whether this is a stylistic difference, or if there is an actual difference in behavior.

Thanks! 

[1]: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md

**Comment by joshuaclayton** [comment]
@jaredbeck the only difference is when the attribute name (in the example above, `invitee`) differs from the sequence name (`email`).

**Comment by jaredbeck** [comment]
@joshuaclayton Thanks, that's what I was hoping. Would you be interested in a PR that updates the docs to clarify this?

**Comment by joshuaclayton** [comment]
@jaredbeck definitely!
