### ISSUE TITLE
What if my model has an attribute named sequence?

### ISSUE THREAD

**Issue by joshco** [thoughtbot/factory_girl#744]
Before I go change my model definition, is there an easy and non-fragile way to do this?
I'm getting an error in the factory because, presumaly, the token sequence is a reserved word.

**Comment by ajm188** [comment]
Alias the `sequence` and `sequence=` methods on your model in spec_helper?

**Comment by drapergeek** [comment]
Not the prettiest solution but you can still use the sequence method and specify your attribute name. You don't have to use the counter provided from the sequence:

```ruby
sequence(:sequence) { "my sequence" }
```
