### ISSUE TITLE
How do I know if my model is being build, created or stubbed?

### ISSUE THREAD

**Issue by brightbits** [thoughtbot/factory_girl#745]
I have `has_many :images`, I want to add some `Image` objects to this. If I do:
```ruby
images { build(:image, 2) }
```
It fails when I try and build_stubbed the object.. 

is there a way of saying "using the current strategy, give me X of these?

**Comment by drapergeek** [comment]
I'm not sure I understand you question but I'll try and give you a few solutions.

With a has_many association, if you want to create associated objects, it's usually best to do it in an `after` hook, you can read more about this here: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#associations

Using those hooks, you can specify whether you want it to happen on build, create or build_stubbed.


If you're just looking to be able to build or create many of them, you can use the `*_list` methods like `build_list` or `create_list`: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#building-or-creating-multiple-records

```
  images = build_list(:image, 2)
```


You still would need to the `after` hooks to assign those, you can't use it as you have in your example above.

Hope that helps, if not please let me know!
