### ISSUE TITLE
Use of FG lint and sequence numbers breaks the generated sequence in tests

### ISSUE THREAD

**Issue by theirishpenguin** [thoughtbot/factory_girl#750]
If we run the linter before the test suite then this causes the seq number to be incremented.

Hence, the sequence number that may get used in a test will start at 2 (instead of 1). This would be fine but for the fact that it appears that if an model is used as an associated object it will be linted again for each time that it is used as an associated object - ruining the consistency of the sequence number.

Am I using this wrong or is there a workaround?

**Comment by theirishpenguin** [comment]
Workaround: Call `FactoryGirl.reload ` after calling `FactoryGirl.lint` in your spec/test setup code.

Feel free to close this issue. I will leave it open in case you think a cleaner solution is warranted.

BTW, I know that relying implicit sequence numbers in a spec is an anti-pattern. But having the linter "disturb" the generated sequence just seems wrong. ie. turning on and off linting could break the test suite, which seems wrong.

**Comment by joshuaclayton** [comment]
@theirishpenguin yes, reloading should fix the issue.

Much to your point, yes, tests asserting against sequential values in a hard-coded fashion in general should be avoided, instead focusing on the restraints/requirements of the data model (e.g. email has to be unique, value doesn't matter).

What you're referring to here at a broader level is considered a [mystery guest](http://xunitpatterns.com/Obscure%20Test.html#Mystery%20Guest), wherein you assert against values that are generated outside of the test itself.

```ruby
FactoryGirl.define do
  factory :user do
    sequence(:email) { |n| "person#{n}@example.com" }
  end
end

RSpec.describe User do
  it "generates an email as a mystery guest" do
    user = build(:user)

    expect(user.email).to eq "person1@example.com" # email address generation occurs somewhere else, unclear where this happens
  end

  it "generates an email explicitly" do
    user = build(:user, email: "example@example.com")

    expect(user.email).to eq "example@example.com" # explicit assignment, clear where email address is coming from
  end
end
```

Mystery guests cause indirection in a test suite and frequently see false failures. Another example of how relying on sequence data would be if the actual sequence values were changed, e.g. moving from `sequence(:email) { |n| "person#{n}@example.com" }` to `sequence(:email) { |n| "person--#{n}@example.com" }`. In both cases, asserting against these values assuming a specific index or interpolation is not ideal.

**Comment by theirishpenguin** [comment]
:+1:
