### ISSUE TITLE
Extending existing factory class by adding more traits.

### ISSUE THREAD

**Issue by chamnap** [thoughtbot/factory_girl#752]
I have a factory class inside another rails engine which defines like this:

```ruby
FactoryGirl.define do
  factory :listing, class: Yoolk::Listing do
    sequence(:name)        { |i| "Name #{i}" }
    sequence(:description) { |i| "Description #{i}" }
  end
end
```

In my Rails application, I want to extend this factory class by adding traits, so that I can invoke like this: `create(:listing, :subscription)`.

```ruby
   trait :subscription do
      after(:build) do |listing, evaluator|
        listing.subscription = build(:subscription)
      end
    end
```

What is the best way to handle this situation?

**Comment by ajm188** [comment]
You can [modify factories](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#modifying-factories) after they've been defined.

**Comment by chamnap** [comment]
Thanks for your reply. Last time, I tried to go through that documentation, but I can't find.

Thanks for pointing out. It's cool with this feature.
