### ISSUE TITLE
Multiple associations in factories

### ISSUE THREAD

**Issue by alec-c4** [thoughtbot/factory_girl#758]
Hi, 
i have a question that i think may extend issue https://github.com/thoughtbot/factory_girl/issues/382. I have following code:

``` ruby
FactoryGirl.define do
  factory :issue do
    association :project
    summary "MyString"
    description "MyText"
    association :priority
    association :issue_type
    association :issue_state
    association :created_by, factory: :user
    assigned_to { created_by } # as you may see - i've used trick from #382 :)
  end
end

FactoryGirl.define do
  factory :issue_state do
    name "MyString"
    association :project
  end
end

FactoryGirl.define do
  factory :issue_type do
    name "MyString"
    association :project
  end
end

FactoryGirl.define do
  factory :project do
    name "name"
    slug "megaslug"
    association :organization
  end
end

FactoryGirl.define do
  sequence(:name)    { |u| "test#{u}" }
  sequence(:slug)    { |u| "test#{u}" }

  factory :organization do
    name
    slug
  end
end

```

I have following problem:
1 - each time i run my test suite - i have a lot of db records. But in my case - i'd like to have each of generated issue_type and issue_state both referencing to the single project. Is it possible?
2 - currently on each run i see error (for project factory as i understand) **Validation failed: Slug has already been taken** - because of each project in scope of his organization should have unique slug. But now - there are problem :(  I've tried to create sequence _slug_ for projects factory, but i saw another error

```
Sequence already registered: slug (FactoryGirl::DuplicateDefinitionError)
```

How can i solve this issues?

**Comment by ajm188** [comment]
1 - I think you're going to need to create the project outside of the factory and then pass it in via the options hash like so:
```ruby
project = FactoryGirl.create(:project)
issue_type = FactoryGirl.create(:issue_type, project: project)
issue_state = FactoryGirl.create(:issue_state, project: project)
```
Of course, you would probably want to extract that out to a helper method.

2 - If you define your sequences inline, they will be defined locally to the factory they were defined in. So:
```ruby
FactoryGirl.define do
  factory :organization do
    sequence(:slug) { |n| "organization_#{n}" }
  end

  factory :project do
    sequence(:slug) { |n| "project_#{n}" }
  end
end
```
You can check out the [docs](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#sequences) for more info.

Let me know if this helps.

**Comment by drapergeek** [comment]
Hi @alec-c4, @ajm188 gave a perfect answer for number 2.

I have a solution that may be helpful for your first issue. I've used this in a few scenarios that are similar to your case:

```ruby
factory :issue_type do
  name "MyString"
  after :build do |model|
    if model.project.blank?
      model.project = Project.first || build(:project)
    end
  end
end
```

This allows you to default to the first project but still allows you to override it in the cases you want a custom one.

Hope that helps!
