### ISSUE TITLE
Getting Started Guide Garbled

### ISSUE THREAD

**Issue by kjbkjb** [thoughtbot/factory_girl#764]
Your stylesheets on the Getting Started guide are collapsing copy on itself in Chrome for OSX. (Haven't tried other browsers)

![factorygirlgettingstarted](https://cloud.githubusercontent.com/assets/1503390/6966203/d2e7f154-d91c-11e4-8909-b98f2abde8a5.png)

**Comment by jaredbeck** [comment]
Looks fine to me in Firefox 37 and Chrome 41.  Can you try disabling extensions and/or resetting (https://support.google.com/chrome/answer/3296214?hl=en)?

**Comment by drapergeek** [comment]
I can't reproduce this either on Chrome, Firefox or Safari.

Please reopen if you're still seeing issues without extensions. If you do have issues, also include the chrome version so we can try and narrow it down.

**Comment by kjbkjb** [comment]
So sorry guys. Thanks for looking. Turns out it is this extension: 
https://chrome.google.com/webstore/detail/markdown-preview/jmchmkecamhbiokiopfpnfgbidieafmd
