### ISSUE TITLE
Misleading error message for bad associations

### ISSUE THREAD

**Issue by ajm188** [thoughtbot/factory_girl#770]
I came across this when I made a mistake in defining my factories. Consider the following models:

```ruby
class Course < ActiveRecord::Base
  has_many :course_instances
end

class CourseInstance < ActiveRecord::Base
  belongs_to :course
  belongs_to :professor
end

class Professor < ActiveRecord::Base
  has_many :course_instances
end
```
I was testing some code for the `Course` model, and was getting a NoMethodError related to a professor object. In my haste, I quickly defined my factories like so:

```ruby
FactoryGirl.define do
  factory :professor do
  end

  factory :course do
    association :professor # This was the mistake that I made
  end
end
```
When I then ran `FactoryGirl.build(:course)` I got a "Factory not registered: professor (ArgumentError)"
This was not a very helpful message, and was actually misleading, as I spent a good while trying to figure out why FactoryGirl wasn't finding the professor factory. A message to the effect of "Invalid/Unknown association in course factory" would have been far more helpful.

**Comment by drapergeek** [comment]
On a new app, I can't seem to reproduce this issue. When I build a new app given your exact setup here and run `build(:course)`, I'm presented with the following error:
```
NoMethodError: undefined method `professor=' for #<Course id: nil, name: nil, created_at: nil, updated_at: nil>
```

What version of FG are you using? Can you provide a small app to reproduce this scenario?

**Comment by ajm188** [comment]
Hmm. I can't seem to reproduce it anymore either. It's entirely possible I did something stupid the first time, like misspell "professors" in the factory definition - should have screenshotted/pastebinned. Oh well, closing this.
