### ISSUE TITLE
Doesn't work with rspec raise_error

### ISSUE THREAD

**Issue by krainboltgreene** [thoughtbot/factory_girl#782]
``` ruby
let(:record) { FactoryGirl.create(:thing, name: "") }

it "fails" do
  expect { record }.to raise_error(ActiveRecord::RecordInvalid, "Name can't be blank")
end
```

Doesn't catch the error that pops up.

**Comment by Kameshwaran** [comment]
It should be like,
```
It "fails" do
  expect { FactoryGirl.create!(:thing, :name => "") }.to raise_exception(ActiveRecord::RecordInvalid, "Name can't be blank")
end
```

**Comment by joshuaclayton** [comment]
@krainboltgreene if you remove the message, does it work? If you call `record` outside the `expect` block, does it raise any exceptions? If so, where are they misaligned?

FactoryGirl doesn't impede in any manner when it comes to this - so any appropriate exceptions should be getting raised.
