### ISSUE TITLE
asking the obvious question: song or movie

### ISSUE THREAD

**Issue by duggi** [thoughtbot/factory_girl#785]
is factory_girl - the gem name -, inspired by the song or the movie?

**Comment by joshuaclayton** [comment]
Closed via https://github.com/thoughtbot/factory_girl/issues/921

**Comment by gogocurtis** [comment]
OMG lol.. and here I thought that it was named in honor of the female Factory workers in WW2 that proved that Woman can do a "man's job" just as well.
