### ISSUE TITLE
Factory for custom database view

### ISSUE THREAD

**Issue by amnesia7** [thoughtbot/factory_girl#786]
My setup is `users` have many `projects` and `projects` have many `tasks`. Tasks are actually setup as nested attributes for each project.

I have merged these together using a database view (with a `project_task` model) and each record in the view returns a task, the task's parent project and the project's parent user. I have cherry-picked the fields in the database view that I want to include rather than including all fields from each of the 3 models. 

I also have a couple of custom fields in the view, eg:
```
GREATEST(tasks.updated_at, projects.updated_at, users.updated_at) AS updated_at
```
My current factories are:
```
factory :user do
  # user fields
end

factory :project do
  # project fields
  user
  tasks       { [association(:task)] }
end

factory :task do
  # task fields
end
```

In my specs I currently need to do:
```
before do
  create(:project)
  @project_task = ProjectTask.first
end
```
Is there a way to create a factory to return the project_task record rather than having to call `create(:project)` and then get the first record?

I tried what was mentioned in https://github.com/thoughtbot/factory_girl/issues/449 but it didn't seem to work with my view not including all fields from each of the associated models/tables.

**Comment by joshuaclayton** [comment]
@amnesia7 for complex multi-dependent record creation, FG can't account for each use case. In the past, I've recommended extracting that into a separate method that manages complex creation/persistence instead.
