### ISSUE TITLE
Why factorygirl?

### ISSUE THREAD

**Issue by adrienbourgeois** [thoughtbot/factory_girl#790]
Ok after all this time using factory_girl (which I find awesome) now I really need to know why did you call it factory_girl?

**Comment by jmks** [comment]
I would guess a reference to https://en.wikipedia.org/wiki/Rosie_the_Riveter ?

**Comment by obfuscoder** [comment]
Mailing list?

**Comment by vrybas** [comment]
(－‸ლ)  @adrienbourgeois is issue resolved? Close pls.
