### ISSUE TITLE
Update wiki page about cucumber

### ISSUE THREAD

**Issue by dkniffin** [thoughtbot/factory_girl#802]
[Cucumber support was deprecated](https://robots.thoughtbot.com/writing-better-cucumber-scenarios-or-why-were), so [this wiki page](https://github.com/thoughtbot/factory_girl/wiki/Cucumber-Helpers) should be updated or removed.

**Comment by cnorm35** [comment]
Updated the wiki page with deprecation notice and link to the blog post

**Comment by joshuaclayton** [comment]
@cnorm35 thanks! I'll close this.
