### ISSUE TITLE
Apparently registered traits not being found

### ISSUE THREAD

**Issue by dermusikman** [thoughtbot/factory_girl#804]
Hi -

I'm running into a weird issue in which it appears that `FactoryGirl.create` is not recognizing a registered trait. Each trait is registered (if being present in `Factory#defined_traits` constitutes being registered?), but one is processed normally, while the other is not found. I'd presume that my trait definition were broken, but it appears to be registered in the factory.

Please see the example rails-console session below.

```
[13] pry(main)> FactoryGirl.factory_by_name(:program).defined_traits.map(&:name).include? :one_trait
=> true
[14] pry(main)> FactoryGirl.factory_by_name(:program).defined_traits.map(&:name).include? :another_trait
=> true
[15] pry(main)> program = FactoryGirl.create(:program, :one_trait, participant: participant, primary_site: site, user: user)
  <SQL REDACTED>
ArgumentError: Trait not registered: one_trait
from /path/to/project/vendor/bundle/gems/factory_girl-4.5.0/lib/factory_girl/registry.rb:24:in `find'
[16] pry(main)> program = FactoryGirl.create(:program, :another_trait, participant: participant, primary_site: site, user: user)
  <SQL REDACTED>
   (0.4ms)  COMMIT
=> #<Program:0x007fd6cd084f20
```

Redacted our code a bit (paranoia, you know), but the associated traits look something like this:
```
trait :one_trait do
  before(:create) do |prog|
    prog.my_important_relation << create(:thing, :argument, program: prog)
  end
end

trait :another_trait do
  start_date { [460,430,400,370].sample..days.ago(now)     }
  end_date   { |prog| prog.start_date + 360                }
end
```

Nearest I can tell, this code should all work, and I'm at a loss as to what may be wrong. Please advise.

**Comment by joshuaclayton** [comment]
@dermusikman hmm - it's tough to tell. Are the traits all defined under the same factory, or is there a blend of nested and "global" (e.g. within the top level `FactoryGirl.define` block)? Are you using `FactoryGirl.modify` anywhere? Have you quadruple-checked the spelling? Can you paste your actual factory files?

**Comment by dermusikman** [comment]
Thanks for the response - I'm no longer with the project.
@mordocai - does this still affect your team? If not, please ask the issue to be closed.
