### ISSUE TITLE
Attributes with similar name root don't use default values

### ISSUE THREAD

**Issue by ngunia** [thoughtbot/factory_girl#809]
edit: Sorry, I think this belongs in factory_girl_rails.

I have a model, Scheduler, with two fields with similar names, `schedule`(a hash with datetime information) and `schedule_id` (a random alphanumeric ID).  If I try to explicitly set `schedule` when calling `FactoryGirl.create(:scheduler)`, `schedule_id` gets set to nil.  There is some issue with both of these attributes in my factory having the same root name, schedule.  I verified this by refactoring `schedule_id` to be `scheid` in my entire codebase, which caused the factory to generate Scheduler objects correctly.

Here is a slightly simplified but complete example of the use case:

    # Runner Factory
    FactoryGirl.define do
      factory :runner, class: Runner do
        _id { Moped::BSON::ObjectId.new }
        run_id { IDHelper::generate_id }
        run  { {"on_datetime" => "2015-03-24T10:55:00Z"} }
        created_at { Time.now }
        updated_at { Time.now }
      end
    end

Standard use case:

    run1 = FactoryGirl.create(:runner)
    puts "run1 is #{run1.inspect}"

result:

    run1 is #<Runner _id: 55e88028f53aab3a50000012, _type: nil, created_at: 2015-09-03 17:15:20 UTC, updated_at: 2015-09-03 17:15:20 UTC, run_id: "2874e9f4ae394dadaa89dc7790a5de32", run: {"on_datetime"=>"2015-03-24T10:55:00Z"}>

In some cases, I need to override the on_datetime attribute:
    
    on_datetime_tomorrow = {"on_datetime"=>(Time.now.utc + 1).iso8601()}
    run1 = FactoryGirl.create(:runner, run: on_datetime_tomorrow)
    puts "run1 is #{run1.inspect}"

This properly updates `on_datetime`, but it causes the run_id evaluate to nil:

    run1 is #<Runner _id: 55e880a0f53aab49b0000012, _type: nil, created_at: 2015-09-03 17:17:20 UTC, updated_at: 2015-09-03 17:17:20 UTC, run_id: nil, run: {"on_datetime"=>"2015-09-03T17:17:21Z"}>

**Comment by t4deu** [comment]
This is a duplicate of the Factory Girl issue, #734
