### ISSUE TITLE
Documentation: Alternate manifestation of "class: ClassName" bug, breaking "eq" (==)

### ISSUE THREAD

**Issue by DreadPirateShawn** [thoughtbot/factory_girl#810]
In the primary README.md, the "Rails Preloaders and RSpec" section describes an `ActiveRecord::AssociationTypeMismatch` error when creating a factory with associations, when using a preloader (in my case, `spork`).

I've encountered an alternate manifestation of this same issue, without associations involved:

**Factory:**
```
FactoryGirl.define do
  factory :location, class: Location do
    name 'United States'
  end
end
```
**Test:**
```
let(:sample) { FactoryGirl.create(:location) }
specify { expect(sample).to eq Location.find(sample.id) }
```
**Failure:**
```
Failure/Error: specify { expect(sample).to eq Location.find(sample.id) }
       
  expected: #<Location id: 42, ..., created_at: "2015-09-06 05:24:21", updated_at: "2015-09-06 05:24:21">
       got: #<Location id: 42, ..., created_at: "2015-09-06 05:24:21", updated_at: "2015-09-06 05:24:21">
       
  (compared using ==)
```

That is, [ActiveRecord equality comparison](http://apidock.com/rails/v3.2.13/ActiveResource/Base/%3D%3D) includes a check for `other.instance_of?(self.class)` which is the part that fails in this scenario. I'm guessing it's the same root cause that manifests as `ActiveRecord::AssociationTypeMismatch` in the association-related failure currently provided.

**If the `class: Location` portion of the factory definition is removed, then the same test succeeds just fine.**

The resolution is the same -- run the suite without the preloader, or to add `FactoryGirl.reload` to the RSpec configuration, as demonstrated in the readme.

Given the alternate method of encountering this issue, it would be very helpful if the "Rails Preloaders and RSpec" section would be fleshed out a bit -- namely, to prominently advise adding `config.before(:suite) { FactoryGirl.reload }` if using a preloader, and then explaining the gist of the underlying reason, showing both the association-related example and the self-comparison example I demonstrate above.

Note: I'm using `rails 4.1.4`, `ruby 2.1.2`, `factory_girl_rails 4.4.1 / 4.5.0`, `rspec-rails 2.14.1`, `spork-rails 4.0.0`. For what it's worth, I tried to create a test within the factory_girl test suite which manifested this repro case, but was unable to -- there's something a bit more subtle about the root cause under the hood that I couldn't suss out, thus the request for someone else to flesh out the documentation accordingly (assuming I'm not crazy :-)).

**Comment by joshuaclayton** [comment]
@DreadPirateShawn hmm, interesting. Without the ability to reproduce, my guess is that there is in fact something more subtle going on here. That's not to say that the docs can't be improved, but it's tough to say what the actual problem is, so I'm hesitant to prescribe solutions to an unknown problem.

That said, we do explicitly force reloading FG with Spring (https://github.com/thoughtbot/factory_girl_rails/commit/b44b6b106b5275b7c6e1329a1530329547ed64d8#diff-013428dd3926c18932d42db3c0a3fc46) to handle cases like this.

I'm going to close this for now; don't hesitate to reopen, though, if you track down how to reproduce this in a vanilla project!
