### ISSUE TITLE
Factory_girl changes type of attribute to String

### ISSUE THREAD

**Issue by navaneeth** [thoughtbot/factory_girl#811]
I have a model which has a field called `category_paths`. It is `JSONB` in postgres.

When I set the `category_paths` from factory_girl, factory_girl is changing the value type to String. Consider the following code, even though I am assigning a `Hash`, it gets changed to `String`.

```ruby
FactoryGirl.define do
  factory :product do
    title "MyString"
    after(:build) do |p|
        p.category_paths = Hash.new
        puts p.category_paths.class # This prints as String
    end
  end
end
```

This is weird and I am not able to figure out what is happening. This works fine when tried from Rails console. The problem happens only when used in factory. Is this how factory_girl works? Or is there a way to control this behavior?

Here is the product model

```ruby
class Product < ActiveRecord::Base
    acts_as_copy_target
    searchkick autocomplete: ['brand'], callbacks: :async
    scope :search_import, -> { includes(:product_offers) }
    has_many :product_offers, autosave: true
    validates :title, presence: true
    validate :validate_category_paths
end
```

**Comment by joshuaclayton** [comment]
@navaneeth FactoryGirl doesn't modify what's written to any value, at any point, unless you explicitly tell it to. My guess is that there's some sort of type coercion occurring on the model itself; you said you'd validated that setting it to a hash in the console, and then reading the class back, returns a `Hash`?

**Comment by joshuaclayton** [comment]
No response; archiving for now. @navaneeth if you're still running into issues, please feel free to reopen the issue.
