### ISSUE TITLE
factory_girl's assignment of attributes always causes `ActiveRecord::Attribute#came_from_user?` to return true

### ISSUE THREAD

**Issue by gkop** [thoughtbot/factory_girl#813]
I don't think this (public!) ActiveRecord method is super frequently used, else I wouldn't be the first one reporting this issue on factory_girl after all these years ;) Not to mention the absence of documentation on the method and it's only used in [exactly one file inside Rails](https://github.com/rails/rails/blob/9f4f08cdc1fb43f9b14d49f32db9a179abc77f6c/actionview/lib/action_view/helpers/tags/base.rb)

Anyhow, since it's a part of ActiveRecord core, I think we should at least document this somewhat surprising behavior.

[Here are the definitions of this method](https://github.com/rails/rails/blob/9f4f08cdc1fb43f9b14d49f32db9a179abc77f6c/activerecord/lib/active_record/attribute.rb)

The method may be more commonly called via [attribute meta methods defined here](https://github.com/rails/rails/blob/9f4f08cdc1fb43f9b14d49f32db9a179abc77f6c/activerecord/lib/active_record/attribute_methods/before_type_cast.rb) (eg. `Article#subject_came_from_user?`)

Maybe I'm thinking about it wrong, but I often depend on factory_girl during the "setup" phase of my automated tests, therefore I would not expect ActiveRecord to think that my factory_girl attributes "came from user."

**Comment by gkop** [comment]
Yea so maybe we just close this. Although if there were a simple way to change how factory_girl assigns attributes (unlikely) that would be nice.

**Comment by joshuaclayton** [comment]
@gkop looking at the other options (e.g. `from_database`), `came_from_user?` seems most appropriate, since FactoryGirl is doing direct attribute assignment behind the scenes.
