### ISSUE TITLE
initialize_with doesn't work with blocks

### ISSUE THREAD

**Issue by atipugin** [thoughtbot/factory_girl#816]
I've a class that strictly requires block to be passed in:

```ruby
module MailBooth
  class List
    attr_reader :name, :options, :block

    def self.define(name, options = {}, &block)
      MailBooth::ListCollection.instance.add(new(name, options, &block))
    end

    def initialize(name, options, &block)
      unless block_given?
        fail MailBooth::Exceptions::UndefinedList,
             "You need to provide a definition of your #{name} list."
      end

      @name = name
      @options = options
      @block = block
    end
  end
end
```

And following factory:

```ruby
FactoryGirl.define do
  factory :mail_booth_list, class: MailBooth::List do
    transient do
      name { FFaker::Lorem.word }
      options Hash.new
    end

    initialize_with { new(name, options) { Time.now } }
  end
end
```

And here is the problem: block is never passed in and calling `FactoryGirl.build(:mail_booth_list)` raises exception. Is there any way to pass a block while factory initialization?

**Comment by Mohit-Pawar** [comment]
Point to Remember
 1. For maximum compatibility with ActiveRecord, the default initializer builds all instances by calling new on your build class without any arguments. It then calls attribute writer methods to assign all the attribute values. 
 2. While that works fine for ActiveRecord, it actually doesn't work for almost any other Ruby class.

 To work with non ActiveRecord object there are 2 options
 1. Use a method other than new to instantiate the instance
 2. Do crazy things like decorate the instance after it's built

So to solve above problem . use a method other than new to instantiate the instance

module MailBooth
  class List
    attr_reader :name, :options, :block

    def self.define(name, options = {}, &block)
      MailBooth::ListCollection.instance.add(new(name, options, &block))
    end

    def initialize(name, options, &block)
      unless block_given?
        fail MailBooth::Exceptions::UndefinedList,
             "You need to provide a definition of your #{name} list."
      end

      @name = name
      @options = options
      @block = block
    end

    def self.build(name, options, &block)
      new(name, options, &block )
    end

  end
end

----------
FactoryGirl.define do
  factory :mail_booth_list, class: MailBooth::List do
    transient do
      name { FFaker::Lorem.word }
      options Hash.new
    end

    initialize_with { MailBooth::List.build(name, options) { Time.now } }
  end
end

**Comment by joshuaclayton** [comment]
@atipugin nice catch, and you're correct; I was able to validate the failure by a test. I've got a PR open to address this, and assuming it's green, it'll be good to merge. Nice catch!

**Comment by atipugin** [comment]
Great! :+1:
