### ISSUE TITLE
Active record association - meta after create callbacks are not called sometimes

### ISSUE THREAD

**Issue by Machiaweliczny** [thoughtbot/factory_girl#817]
Given I have some ActiveRecord model:
```
class Foo < ActiveRecord::Base
 has_one :bar
 after_create :create_bar

 def some_method
   bar(true).property
 end
end
```

I have randomly failing tests on CI in this scenario:
```
foo = create(:foo)
foo.some_method
```
Error is:
```
undefined method `property' for nil:NilClass (NoMethodError)
```
So association is not loaded somehow :/

Unfortunatelly I haven't tracked the issue yet, but I think it might be connected with usage of factory girl. Is it possible that you have bug here or should I rather ask on Rails project?

I'm using:
```
gem 'rails',              '~> 4.1.8'
gem 'factory_girl_rails', '~> 4.4.1'
```

**Comment by Mohit-Pawar** [comment]
@Machiaweliczny 
Can you specify how factories are defined.

**Comment by joshuaclayton** [comment]
@Machiaweliczny I'd try to interact with the AR code independent of FactoryGirl to see if you're running into the same thing; if you are, it's something outside of FactoryGirl.

I'm going to close this for now, but if you learn more or narrow it down to FactoryGirl, don't hesitate to re-open.
