### ISSUE TITLE
FactoryGirl and JSONAPI

### ISSUE THREAD

**Issue by joshuaclayton** [thoughtbot/factory_girl#819]
I've recently been using [JSONAPI::Resources](https://github.com/cerebris/jsonapi-resources) on a project and have been using RSpec's request specs to test some of the basic endpoints, especially for POST and PATCH requests.

The basic structure is such that I'd make a request with a hand-built hash that I'd call `to_json` on - not super great, especially when having to include the belongs-to relationships.

I whipped this together to get something to work and it seems to handle basic factories/relationships, including polymorphic belongs-to's:

```ruby
module FactoryGirl
  class AttributeAssigner
    def api_hash
      @evaluator.instance = build_hash

      attributes_to_set_on_instance.inject({}) do |result, attribute|
        association = association_names.include?(attribute)
        result[attribute] = OpenStruct.new(name: attribute, value: get(attribute), association?: association)
        result
      end
    end
  end

  class Evaluation
    delegate :api_hash, to: :@attribute_assigner

    def build_class
      @attribute_assigner.instance_exec { @build_class }
    end
  end
end

class JSONAPIPayloadStrategy
  def initialize
    @created_records = {}
  end

  def association(runner)
    relationship_from_record(runner.run(:create))
  end

  def result(evaluation)
    new_hash = evaluation.api_hash.inject({}) do |result, (key, val)|
      value = val.value

      if val.association?
        self.created_records.merge!(relationship_from_record(value, val.name))
      else
        result[key.to_s.dasherize.to_sym] = value
      end

      result
    end

    {
      data: {
        type: evaluation.build_class.name.tableize.dasherize,
        attributes: new_hash,
      }
    }.tap do |payload|
      if created_records.any?
        payload[:data][:relationships] = created_records
      end
    end
  end

  protected

  attr_reader :created_records

  private

  def relationship_from_record(record, key = nil)
    if record
      if record.is_a?(Hash)
        record_type = record[record.keys.first][:data][:type]
        record_id = record[record.keys.first][:data][:id]
      else
        record_type = record.class.name.tableize.dasherize
        record_id = record.id
      end

      response = {}

      response[(key || record_type).to_s.singularize.to_sym] = {
        data: {
          type: record_type,
          id: record_id.to_s,
        }
      }

      response
    else
      {}
    end
  end
end

FactoryGirl.register_strategy(:json_api, JSONAPIPayloadStrategy)
```

It's used as such:

```ruby
  context "POST" do
    it "posts and calculates the user correctly" do
      user = create(:user)

      as_user user do
        post "/api/endpoint",
          FactoryGirl.json_api(:model, name: "New group", user: nil).to_json
      end

      expect(payload[:data][:attributes][:name]).to eq "New group"
```

A couple things going through my head:

This doesn't handle has-many relationships right now - partly due to FG not doing so directly (apart from callbacks+transient attributes), but it'd be cool if you could do something like:

```ruby
tags = create_list(:tag, 5)
FactoryGirl.json_api(:post, title: "I have five tags!", tags: tags)
```

This also seems potentially brittle, especially if the API greatly differs from the attributes on a given model. I'm not super concerned about this, since it seems there's little modification you'd want to do between the two anyway, but it still crossed my mind.

Finally, I'm concerned I'm reinventing the wheel here - I'm not familiar enough with `JSONAPI::Resources` to know if it can craft payloads it would be able to accept to its appropriate endpoints, but if there was a way to basically build a hash or object instance and leverage it to build out a payload, even better.

@cerebris pinging you on the JSONAPI::Resources side (not sure if there's anyone else better suited to participate here) - I'd love/appreciate any insight you might have on constructing the payloads somehow.

**Comment by lgebhardt** [comment]
In [JSONAPI::Resources](https://github.com/cerebris/jsonapi-resources) we hand code the payloads for the tests because I want to be sure of the specific test conditions, including invalid structures. So the JSONAPI::Resources doesn't contain any sort of helper you could use to generate payloads.

What you're proposing would be a very useful library. I think the likelihood of the API differing from the model is high, given what I've seen of how people are using JR. So I'd try to make any solution base the payloads off the project's resources and not the models. You could probably get creative with the fields and include options and use the ResourceSerializer to generate valid payloads, though this may not give you the flexibility you need for all the tests.

**Comment by joshuaclayton** [comment]
As I haven't used JSONAPI (within Ruby) recently, I'm going to close this for now.

**Comment by pixelhandler** [comment]
@joshuaclayton I just use JSON fixture files for request specs.
