### ISSUE TITLE
Build instead create association using build strategy

### ISSUE THREAD

**Issue by victor95pc** [thoughtbot/factory_girl#820]
Hi guys, I really enjoy all your wok on this gem, but there is a problem when it comes to create association in factories, when I call FactoryGirl.build(or just build), I expect FactoryGirl build the associations and not save on the database, because most of the time I just need the data for a small validation.

I don`t know if you guys already created and closed a issue for this, but I didn't find a config var to set association to build when I use a specific strategy, so I made a little **ugly** hack:
```ruby
#File lib/factory_girl/evaluator.rb, line 24
    def association(factory_name, *traits_and_overrides)
      overrides = traits_and_overrides.extract_options!
      strategy_override = overrides.fetch(:strategy) do
        if @build_strategy.is_a? FactoryGirl::Strategy::Build
          :build
        else
          :create
        end
      end

      traits_and_overrides += [overrides.except(:strategy)]

      runner = FactoryRunner.new(factory_name, strategy_override, traits_and_overrides)
      @build_strategy.association(runner)
    end
#...
```
I know there is a way to make this code better :wink:, but what do you guys think? is it a good idea?
Thx for your attention and sorry for my poor English

**Comment by Mohit-Pawar** [comment]
Hi @victor95pc 
If you do not want to save the associated object, specify strategy: :build in the factory:
For example
factory :post do
  association :author, factory: :user, strategy: :build
end

# Builds a User, and then builds a Post, but does not save either
post = build(:post)
post.new_record?        # => true
post.author.new_record? # => true

see documentation of Associations in Factory Girl

**Comment by victor95pc** [comment]
@Mohit-Pawar I know that, but why dont  association by default, instead write strategy: :build in every factory.

My solution on that code above is to build association when call build(:post) and create association when you call create(:post)

**Comment by joshuaclayton** [comment]
@victor95pc I'd keep an eye on https://github.com/thoughtbot/factory_girl/pull/749; we plan on addressing this in a future release.
