### ISSUE TITLE
Ordering of String sequences

### ISSUE THREAD

**Issue by jhanggi** [thoughtbot/factory_girl#821]
I've now run into this on three separate projects. We commonly use a sequence for creating names for our records (to avoid uniqueness constraints), and we're often testing against a specific ordering of results.

`sequence(:name) { |n| "name #{n}" }`

We'll often have some similar scope:

```
def self.ordered
  order(:name)
end
```

Everything works when the test runs in isolation, but if we run a full test suite, we run into transient test failures where `"name 100" < "name 99"` when the test runs across that three digit/four digit border. We tried using `sequence(:name, "a")`, but that still runs into a similar problem when we cross the 26-item border. We can solve this by changing our sequence to:

`sequence(:name, "aaaaaaa") { |n| "name #{n} }`

giving us millions of options, so we'll likely never hit the border of `zzzzzzzz`, `aaaaaaaaa` (8 "z" vs 9 "a"), but it is theoretically possible.

Is there a smarter way to solve this across the board, or would it be possible to make a default for string-based sequences so if you said `sequence(:name, "a")`, it always started with a long string (10-12 characters)?

We're working with a lot of legacy codebases where FactoryGirl has been in place for a long time, and we're only recently forcing the use of CI in our development process, so these intermittent failures are popping up more and more. 

Maybe the best solution is improved documentation around `sequence` regarding its use in strings. If someone has a recommended place for that documentation, I'm happy to build a PR around it.

**Comment by joshuaclayton** [comment]
@jhanggi I'm going to close this issue, deferring to conversations on each of the other PRs for the various conversations about this.
