### ISSUE TITLE
#build (et al) documentation is outdated

### ISSUE THREAD

**Issue by rstacruz** [thoughtbot/factory_girl#824]
in https://github.com/thoughtbot/factory_girl/blob/03786660edbe4e028a292d19f7956f8dd0c89347/lib/factory_girl/syntax/methods.rb :

```
      # @!method create(name, *traits_and_overrides, &block)
      # (see #strategy_method)
      # Creates a registered factory by name.
      # @return [Object] instantiated object defined by the factory
```

it references `#strategy_method` which doesn't exist anymore.

**Comment by joshuaclayton** [comment]
@rstacruz interested in making a PR? This is now handled in this file: https://github.com/thoughtbot/factory_girl/blob/03786660edbe4e028a292d19f7956f8dd0c89347/lib/factory_girl/strategy_syntax_method_registrar.rb

**Comment by rstacruz** [comment]
i know very little of factory_girl internals, sorry. :(
