### ISSUE TITLE
Passing in false for an attirbute in a :create does not seem to persist

### ISSUE THREAD

**Issue by sgringwe** [thoughtbot/factory_girl#831]
It seems that if you pass in false for an attribute, such as ```FactoryGirl.create(:book, read: false)``` does not actually set 'read' to false and instead uses the factory default value. Is this expected?

**Comment by vemv** [comment]
Your diagnose is wrong - FG will happily accept and set `false` values.

Sample from my codebase, where I have a postgresql boolean column:

```
FactoryGirl.create(:campaign, skip_past_date_validations: true).skip_past_date_validations
=> true
FactoryGirl.create(:campaign, skip_past_date_validations: false).skip_past_date_validations
=> false
```

Create a failing test in a branch or close the issue, to save everyone time.

Victor

**Comment by joshuaclayton** [comment]
@sgringwe sounds like there might be something else going on within your models. I'd read over https://github.com/thoughtbot/factory_girl/wiki/How-factory_girl-interacts-with-ActiveRecord, try and perform the same steps (sans FG) and report back. Until then, I'll close this issue. Thanks!
