### ISSUE TITLE
Circular associations cause seg fault

### ISSUE THREAD

**Issue by LukeLaupheimer** [thoughtbot/factory_girl#832]
When you create a circular association chain, and try to generate an instance of one of the factories within it, FactoryGirl throws a segmentation fault. Here's some code that will reproduce the error

```ruby
FactoryGirl.define do
  factory :flooble_crank do
    association :blooble_yank
  end

  factory :blooble_yank do
    association :flooble_crank
  end
end

class FloobleCrank
end

class BloobleYank
end

fc = FactoryGirl.create(:flooble_crank)
```

Would it be possible to correct this such that when a circular association chain is invoked, it stops when the loop is about to start again?

You might be able to accomplish this with some kind of breadcrumb, where a hash of all the factories invoked thus far in this FactoryGirl.create chain are logged, and when it's about to re-invoke FactoryGirl.create on an instance that's already been created, it just associates the model with that initial object.

If someone on the outside made a crack at something to this effect and submitted a pull request for it, would such a feature be included?

(This thread is meant to be a feature request and discussion of if the feature is viable in the first place, and why/why not)

**Comment by Fourfingerz** [comment]
Can you give me a real world example of which you would run into this problem? I haven't had an instance where I would use a has_one association for both ends personally. It would be really interesting to see if this is a common use case enough that it becomes a real problem with FactoryGirl.

**Comment by hut8** [comment]
I tried this because I didn't believe that it causes a segfault :stuck_out_tongue: 
I get a `SystemStackError` here which is what I expected. I don't think this is a bug since I expected that to happen. I'm on MRI 2.2.1 with factory_girl 4.5.0

**Comment by joshuaclayton** [comment]
@LukeLaupheimer I'm going to close this for now; circular relationships will raise exceptions, but should not be causing segfaults. If you could point to a repository demonstrating this, it'd definitely help us better understand what you're seeing. Until then, I'm going to close out this issue. Thanks!
