### ISSUE TITLE
build_stubbed strategy should set changes to empty

### ISSUE THREAD

**Issue by randoum** [thoughtbot/factory_girl#837]
Greetings,

Currently when creating a record with `build_stubbed` it has `changes` populated as if it was a non persisted object.

```ruby
user = build_stubbed :user, name: 'Joe'
user.changes
# => {"name"=>[nil, "Joe"]}
user.name_was
# => nil
```

As `build_stubbed` is supposed to mimic a persisted object without accessing the database, a correct behaviour would be to have its `changes` empty.
I can simulate this by doing the following:

```ruby
user = build_stubbed :user, name: 'Joe'
user.clear_changes_information
user.changes
# => {}
user.name_was
# => "Joe"
```

So my questions:
- Would you agree with me on the expected behaviour?
- If yes, could you point me to the right direction to implement this in FG source so I can post a PR?

**Comment by quadule** [comment]
I just ran into this today and I agree with your reasoning: I would expect a record returned by `build_stubbed` to be unchanged as it would if it was loaded through ActiveRecord.

Any maintainers care to comment? Thanks!

**Comment by randoum** [comment]
Closing. Related PR on going: #838
