### ISSUE TITLE
First Time Contributing

### ISSUE THREAD

**Issue by GustavoCaso** [thoughtbot/factory_girl#841]
@joshuaclayton Is there any lables or good first issues to get started contributing to the project ?

Thanks.

**Comment by arumoy-shome** [comment]
:+1:

**Comment by joshuaclayton** [comment]
@GustavoCaso No, there's nothing in place currently, actually. We do have a [contributing document](https://github.com/thoughtbot/factory_girl/blob/master/CONTRIBUTING.md) that would be a good place to start regarding the code of conduct.

I haven't had an investment day to work on FG in a while, so I might take a look at this in the coming weeks to see if I can put anything together. I'd say the majority of what's out there either requires significant discussion, or explanation of how to extend FG without updating the internals.
