### ISSUE TITLE
[Question] Is there a mechanism to have RSpec use Factory Girl for its implicit subject?

### ISSUE THREAD

**Issue by AaronRustad** [thoughtbot/factory_girl#842]
Just curious if there is a way to have RSpec use a know factory as the implicit subject for a set of tests.

So, instead of:

```ruby
RSpec.describe PreferredTerm, type: :model do
...
end
```
...one might be able to do something like...
```ruby
RSpec.describe PreferredTerm, factory: :preferred_term do
...
end
```

Thanks!
AR

**Comment by sikachu** [comment]
There is currently none.

I personally don't think it's a good idea given you probably have to have a default build strategy? I'm not sure if FG should `build`, `build_stubbed`, or `create` in that case. It's also much clearer to just do `subject { }` block within that describe block.

**Comment by AaronRustad** [comment]
I guess I see that Rspec has a "default build strategy" already when it calls `Model.new` when defining the implicit `subject`. By defining `factory: :factory_name`, you'd be replacing the default mechanism. 

I suppose one could extend the idea a little further to include the build strategy:
```ruby
RSpec.describe PreferredTerm, factory: :create_preferred_term do
...
end
```

In any case, as you suggested `subject { }` works too, and that's fine by me....for now.  :wink: 

Thanks!
AR

**Comment by joshuaclayton** [comment]
@AaronRustad this might be something that RSpec itself supports, but I'm not familiar with it.

Additionally, though, I'd probably avoid using default subjects that interact with FG - at a unit test level, it's actually very unlike you'll want to use FG. I've written about this topic here: https://robots.thoughtbot.com/speed-up-tests-by-selectively-avoiding-factory-girl
