### ISSUE TITLE
Allow factory overriding of atributes ending with _id along with attributes with same prefix (without the _id)

### ISSUE THREAD

**Issue by ticolucci** [thoughtbot/factory_girl#851]
Disclaimer: the code below has a lot of smells, but they are intended to show the possible issue with the way FactoryGirl allows attribute overriding on instantiation.

The issue apparently is that overriding both attributes ending in "_id" and it's "alias" (attribute name without _id) ends up not overriding them at all, leaving the object with the `klass.new` state.

Here follows a spec that fails on a bare bone ruby project. Details about my spec run:
* Gemfile containing only factory_girl [4.5.0] and rspec [3.4.0]
* ruby version: 2.2.3p173
* running an OSX 10.11.2

```ruby
require 'factory_girl'

class Address
  attr_accessor :id, :street
end

class User
  attr_accessor :address, :address_id, :address_street
end

FactoryGirl.define do
  factory(:address) do
    id { 42 }
    street { "Street 42" }
  end

  factory(:user) do
    address { FactoryGirl.build(:address) }
    address_id { address.id }
    address_street { address.street }
  end
end

RSpec.describe 'Factories without association, without rails, without magic' do
  it 'creates factories with no overriding' do
    correct_user = FactoryGirl.build(:user)

    expect(correct_user.address.street).to eq 'Street 42'
    expect(correct_user.address.id).to eq 42
  end

  it 'allows one overriding' do
    someone = FactoryGirl.build(:user, address: FactoryGirl.build(:address, id: 23, street: "A special Street"))

    expect(someone.address.street).to eq 'A special Street'
    expect(someone.address.id).to eq 23
  end

  it 'allows overriding of NOT "(.*)_id" attributes and "\1" at the same time' do
    another_address = FactoryGirl.build(:address, id: '30', street: "Another Address")
    another_person = FactoryGirl.build(:user, address: another_address, address_street: another_address.street)

    expect(another_person.address.street).to eq "Another Address"
    expect(another_person.address.id).to eq '30'
  end

  it 'allows overriding "(.*)_id" attributes and "\1" at the same time' do
    mystery_address = FactoryGirl.build(:address, id: '221B', street: "Baker Street")
    detective = FactoryGirl.build(:user, address: mystery_address, address_id: mystery_address.id)

    expect(detective.address.street).to eq "Baker Street"
    expect(detective.address.id).to eq '221B'
  end
end
```

My main question before digging deep into FactoryGirl code is: Is this a valid bug or am I missing some documentation?

**Comment by ticolucci** [comment]
After looking further in the closed issues, I found references pointing to this issue in `factory_girl_rails`: thoughtbot/factory_girl#734

I can understand how this might be important for AR and other frameworks, but we're using factory girl as an API response generator... While I understand that it might not be the main usage for most people, I also do not see why the magic is that important, I do not fully agree that it's a desired feature even while using ActiveRecord.

In case a core dev closes this issue, here's a work around that we'll might end up using in the current project:

```ruby
FactoryGirl.aliases = [
  [/([^(?:address)].+)_id/, '\1'],
  [/([^(?:address)].*)/, '\1_id'],
]
```

**Comment by joshuaclayton** [comment]
Yes, I think it makes sense to bypass what's going to be a 99.99% correct behavior when deviating from standards. In the future, I could see the _id aliasing being something that's more of a configuration setting (that's handled in factory_girl_rails), but for now, your solution makes sense.
