### ISSUE TITLE
Building lists with mixed attributes

### ISSUE THREAD

**Issue by tkeifer** [thoughtbot/factory_girl#853]
I'm looking for a more elegant way of doing the following...

data = [{ admin: true },{ admin: false }]
users = data.map { |u| FactoryGirl.create(:user, u) }

I've tried using build_list and specifying a hash, but this assigns the *same* value to every record. This was the only solution that Google turned up as well, but it gets repetitive and seems like there should be an easier way. 

Thanks

**Comment by joshuaclayton** [comment]
@tkeifer for this example specifically, I'd probably have user default to a normal (non-admin) user, and create an admin trait, then do `[create(:user), create(:user, :admin)]`; are you commonly trying to build multiple factories with disparate sets of attributes?

**Comment by tkeifer** [comment]
I will give that a shot, thanks! It seems like this does come up a lot when testing controllers that are performing filtering. Being able to build a group, with differing attributes helps test that code. (though there may be a better way of doing this)

**Comment by joshuaclayton** [comment]
Closing this for now; @tkeifer if you're still running into issues, don't hesitate to reopen!
