### ISSUE TITLE
Using a "Hash" factory screws up non Hash factories

### ISSUE THREAD

**Issue by jtmarmon** [thoughtbot/factory_girl#858]
```rb
FactoryGirl.define do
  factory :foo, class: Hash do
    data 'abc'
  end
  initialize_with { attributes }
end
```

```rb
FactoryGirl.define do
  factory :bar, class: SomeActiveRecordModel do
     someattribute 'bar'
  end
end
```

If I do `FactoryGirl.create(:bar)` I get `undefined method save! for #<Hash:0x007fb9d9de5f90>`

**Comment by KirillKayumov** [comment]
```ruby
  factory :bar, class: SomeActiveRecordModel do
     foo 'bar'
```
@jtmarmon When you define a factory for ActiveRecord model you specify name of attribute and it's default value, so **foo** – attribute name, **'bar'** – value. Why do you try instead of attribute name pass name of factory which builds Hash? I can't imagine use case for this.

**Comment by jtmarmon** [comment]
my goal in the above example is not to use the `foo` factory. just a bad example. i'll update the attribute name accordingly so it's less confusing

**Comment by joshuaclayton** [comment]
@jtmarmon I think you're looking for `skip_create`: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#custom-methods-to-persist-objects

Feel free to reopen if you're still running into issues.

**Comment by dani07** [comment]
@jtmarmon Did you figure out what was wrong?

**Comment by NikolaiKircher** [comment]
In case anyone else stumbles upon this:

I think the problem was that `initialize_with { attributes }` is defined outside of the Hash factory and therefore in the global FactoryGirl context.

This worked for me:
```
FactoryBot.define do
  factory :foo, class: Hash do
    data 'abc'

    initialize_with { attributes }
  end
end
```
