### ISSUE TITLE
undefined method `type' for #<Venue:0x007fed071c86c0>

### ISSUE THREAD

**Issue by shesko** [thoughtbot/factory_girl#861]
I created a venue model that had a column called type. Eventually I got a error from rails because type is a reserved keyword. I then changed the column name to venue_type and I am getting this error:
```
Failure/Error: @venue = FactoryGirl.create :venue
     NoMethodError:
       undefined method `type' for #<Venue:0x007fed093b9a18>
     # ./spec/controllers/api/v1/venues_controller_spec.rb:6:in `block (3 levels) in <top (required)>'
```
Any idea why is it so ? This is my factory_girl file:

```
FactoryGirl.define do
  
  factory :venue do
    name { FFaker::Product.product_name }
    venue_type "2"
    phone_number { FFaker::PhoneNumber.phone_number }
    email { FFaker::Internet.email }
    description "This is a string and I can't be bothered to use FFaker"
  end
end
```

**Comment by shesko** [comment]
right, turns out I accidentally did undo in the model file and tries to validate the old "type" column. Sorry about that

**Comment by joshuaclayton** [comment]
thanks for following up @shesko! My suggestion was going to be to check that the test database was migrated; glad you got it cleared up!
