### ISSUE TITLE
4.4.0->4.5.0 include non backward compatible changes

### ISSUE THREAD

**Issue by jahoo** [thoughtbot/factory_girl#862]
Changing `send` to `public_send` is not backward compatible.

It is rather major change. Shouldn't it be reverted and released in major update (e.g. 5.0.0)?

**Comment by dre-hh** [comment]
Let's rather revert it back. A factory girl should know how stuff is build within the factory.

**Comment by joshuaclayton** [comment]
Given the revert complexity, I don't think it makes sense to do so now. I'd stick with 4.4, make whatever methods public (or remove the dependency on calling private methods), and upgrade when it makes sense.
