### ISSUE TITLE
Disallow classes be used for factory lookup

### ISSUE THREAD

**Issue by joshuaclayton** [thoughtbot/factory_girl#871]
Based on the discussion in https://github.com/thoughtbot/factory_girl/pull/843, and from other thoughts around simplifying FG's interface, I think we should deprecate the ability to find a factory based on class.

@monkbroc had mentioned interest in deprecating this behavior.

@monkbroc here's an example of a feature flag: https://github.com/thoughtbot/factory_girl/commit/a5b3a97c9d72090c4a0d814a84077634184774a2 and the removal in prep for a major release (along with other changes!): https://github.com/thoughtbot/factory_girl/commit/e9d9e3099b65e08ae18988c8f3f9a39b09a60902

My thought is that we'll want to:

1. Ensure there's an acceptance test around factory lookup by class
2. Introduce a flag disallowing that behavior available in FG's configuration
3. Introduce a test where, with the flag set, it raises a 'factory not found' exception
4. Introduce a deprecation warning when we actually do look up by class
5. Silence deprecation warnings in the appropriate tests

I'm not sure I have an opinion as to whether we also disallow string lookup as well, only allowing symbols, but it's another level of specificity I wouldn't be opposed to introducing.

**Comment by monkbroc** [comment]
I'll take a crack at this.
