### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by conf** [thoughtbot/factory_girl#872]
Hello guys,

Can you share your plans on next release date, please? It's been a while since the last release in Oct 2014, and I'd very like to see new FactoryGirl release (especially additional data in instrumentation changes).

Thanks!

**Comment by olliebennett** [comment]
Ditto. I'm missing the `traits: true` option of `FactoryGirl.lint` (i.e. [this](https://github.com/thoughtbot/factory_girl/pull/800)) which is present on `master` (and is documented in the README) but is not yet released. :+1: Thanks

**Comment by drapergeek** [comment]
Looks like this was released in https://github.com/thoughtbot/factory_girl/releases/tag/v4.7.0

**Comment by conf** [comment]
Yay! Thanks for notifying! ❤️
