### ISSUE TITLE
Possible memory pollution?

### ISSUE THREAD

**Issue by gamov** [thoughtbot/factory_girl#876]
I've just upgraded an app to Rails 4 and I have now a few tests failing when invoked via test:units but pass when just running the test file. I spent many hours in the debugger to isolate the problem. It is present under Rails 3.2 but was not affecting the test (for reasons, see below).

I'm writing to see if I'm not doing anything stupid and for future reference.
I have a factory set this way:
```ruby  
factory :user do
    association :person
    sequence(:username) {|n| "user#{n}"}
    password 'password'
    password_confirmation 'password'

    User.valid_roles.each do |role|
      factory role do
        role_username = role
        sequence(:username) { |n| "#{n}_#{role_username}".slice(0..11) }

        roles_mask User.mask_for(role)
      end
    end
```
Is this legal? Basically, it creates a factory for each role defined.
**The Issue**
The following very vanilla model is defined with its factory
```ruby
#= model ===
class IntendingOrder < ActiveRecord::Base
  belongs_to :requester, class_name: 'User'
end
#= factory === (notice that there is absolutely no mention of the 'requester' association):
  factory :intending_order do
    quantity_intended { rand 3..100 }
  end
```
Finally, in my test file: 
```ruby
new_io = FactoryGirl.create :intending_order # again, NO mention of requester
new_o.save!
```
When I run this test via test:units, this mysteriously happens!!
```ruby
new_io.requester.attributes = # instead of nil!
'id' => nil
'roles_mask' => 8192
'username' => 5_site_order
'password_digest' => {BCrypt::Password} $2a$04$.bfWHkALICRruQoHHTi3dudOB4WzUmh1g/xC0xjl9w/5OlDumHCuu
'inactive' => false
'person_id' => 19
'business_site_id' => 9
'flags' => nil
```
Note that the Person.find(19) doesn't exists...

PS: The difference between Rails 3.2 and Rails 4.0 is that the requester has an id (13) even though it doesn't exist in the database but that fools ActiveRecord not to save it. Under Rails 4, ActiveRecord will attempt a partial write and since no attributes changed, it will crash writing an empty array to the DB.

PS2: factory_girl 4.5, rails 4.0.13, ruby 1.9.3

**Comment by joshuaclayton** [comment]
@gamov I'd avoid iterating over roles in a factories file, instead building those roles manually.

Additionally, you'll want to be sure to use block syntax for any dynamic portions of the factory (e.g. `roles_mask { User.mask_for(role) }`.

Let me know if you're still running into issues; closing this for now.
