### ISSUE TITLE
Reserved word attributes: documentation for add_attribute

### ISSUE THREAD

**Issue by andynu** [thoughtbot/factory_girl#879]
FactoryGirl errors in a number of ways if you have an attribute that is a reserved word. 

>```
factory :payment do
  method 'paypal'
end
```

> .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/definition_proxy.rb:122:in `sequence': wrong number of arguments (0 for 1+) (ArgumentError)


>```
factory :dna do
  sequence { "GATTACA" }
end
```

> factories.rb:23:in `method': wrong number of arguments (0 for 1) (ArgumentError)

You can use sequence to override as mentioned in [this closed ticket](https://github.com/thoughtbot/factory_girl/issues/744). This works for both examples.

```
factory :dna do
  sequence(:sequence) { "GATTACA" }
end
```

This method is not in the documentation anywhere and as @drapergeek mentions in the ticket is "not the prettiest solution." I agree. It seems there is still an add_attribute method in FactoryGirl::DefinitionProxy that seems to work, but is not mentioned anywhere in the wiki. 

```
factory :dna do
  add_attribute(:sequence) { "GATTACA" }
end
```

I think some documentation is all that is needed.  If you agree I'd be happy to work up a PR for the wiki.

**Comment by joshuaclayton** [comment]
@andynu Great point. I think the GETTING_STARTED doc might be a better place to put this, in a section titled `Reserved Method Names` or something similar. Fascinating that we don't have public docs on `add_attribute` - that seems like a think we should include!

**Comment by hakunin** [comment]
It took a while to find this, leaving a note for future googlers:
```
`color': wrong number of arguments (0 for 2) (ArgumentError)
```
