### ISSUE TITLE
create_list without the count should give a proper error message

### ISSUE THREAD

**Issue by tejasbubane** [thoughtbot/factory_girl#889]
Sometimes I forget to pass in the count attribute for `create_list` (eg. when I change `create` to `create_list` and I forget to add the count):
```ruby
create_list(:user, profile: profile)
```

The error in this case is:
```
Failure/Error: create_list(:user, profile: profile)

     NoMethodError:
       undefined method `times' for #<Hash:0x007fda3bd50738>
# /Users/tejas/.rvm/gems/ruby-2.3.0@oudux/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block in define_list_strategy_method'
```

I feel this error should be a little more elaborate saying something like the `create_list` method expects a count.

FactoryGirl version in use here: `4.5.0`

**Comment by Charizard** [comment]
Agreed 👍
