### ISSUE TITLE
Unnecessary sqlite3 dependency?

### ISSUE THREAD

**Issue by theoretick** [thoughtbot/factory_girl#907]
Hey there!

I just noticed FactoryGirl's Gemfile [lists sqlite3 and an activerecord adapter as a project dependency](https://github.com/thoughtbot/factory_girl/blob/master/Gemfile#L5-L8) and as far as I can tell, they are unnecessary ones. It looks like its used in the `features` and `specs`, so maybe this could just be moved to a development dependency. It would be great to remove such a requirement from the library itself.

Is there a reason I missed this these are project dependencies?

**Comment by drapergeek** [comment]
Hi @theoretick 

Those dependencies aren't required for the gem, they're only in there for developing and testing locally. The tests are ran against MRI and jruby and so during different test suite runs, we need different versions. The gemspec doesn't allow us to specify different versions but the Gemfile does.
It looks like the only thing we actually depend on in a user's application is activesupport: https://github.com/thoughtbot/factory_girl/blob/master/factory_girl.gemspec#L23

@joshuaclayton can you confirm that I understood this correctly?

**Comment by joshuaclayton** [comment]
@drapergeek @theoretick yes, you're correct, the only hard dependency is [ActiveSupport](https://github.com/thoughtbot/factory_girl/blob/4a4a0b90f278f48298ef97a12425e1a120cb8abd/factory_girl.gemspec#L23).

The gems you're seeing outlined in the Gemfile are for us using Bundler locally for development purposes.
