### ISSUE TITLE
how to create using transient attributes and regular in the same expression?

### ISSUE THREAD

**Issue by Fedcomp** [thoughtbot/factory_girl#912]
```ruby
class PhoneNumber < ActiveRecord::Base
  belongs_to :user, inverse_of: :phone_numbers
end

FactoryGirl.define do
  factory :phone_number do
    sequence(:number) { |n| "+1333#{n.to_s.rjust(7, '0')}" }

    transient do
      confirmed false
    end

    after(:build) do |phone, evaluator|
      phone.confirmed_at = Time.now if evaluator.confirmed
    end
  end
end

create(:phone_number, confirmed: true, user: user)
```
sadly, this does not work. How can i combine transient attributes and regular ones in one create expression?

**Comment by drapergeek** [comment]
Hi @Fedcomp this should work as you're excepting. I tossed together a quick sample app and seemed to be able to accomplish the same task.

Can you explain more of what the problem you're seeing is?

**Comment by joshuaclayton** [comment]
Closing due to in activity. @Fedcomp if you have any updates, please don't hesitate to provide details. Thanks!

**Comment by Fedcomp** [comment]
Hello. Sorry for outdated response. I can't seem to reproduce it at this moment. My guess it that i used older version of the gem at moment of posting (not fresh even at moment of opening the issue).
