### ISSUE TITLE
build error according to readme badge

### ISSUE THREAD

**Issue by matkoniecz** [thoughtbot/factory_girl#913]
https://github.com/thoughtbot/factory_girl#factory_girl---

**Comment by JasonLunn** [comment]
A month later, this is still red. Is FactoryGirl still an active project, @joshuaclayton ?

**Comment by joshuaclayton** [comment]
@JasonLunn it is! I've personally been busy on other projects recently, though, and FactoryGirl is a community effort. Are you interested in helping by working on this issue?
