### ISSUE TITLE
Create method fails, gives connection error

### ISSUE THREAD

**Issue by encouracadopotemkin** [thoughtbot/factory_girl#914]
I have the following models:

`class User < ActiveRecord::Base`
`  has_many :user_buildings`
`  has_many :buildings, through: :user_buildings`
`end`

`class Building < ActiveRecord::Base`
`    has_many :user_buildings, primary_key:  "building_id"`
`    has_many :users, through: :user_buildings`
`end`

`class UserBuilding < ActiveRecord::Base`
`  belongs_to :users`
`  belongs_to :buildings`
`end`

I tried several ways of creating these factories, but I always had the same problem: if I used the method create for any of them, it gave me this error:

>     Failure/Error: @user = create(:user)
>     
>     Errno::ECONNREFUSED:
>       Connection refused - connect(2) for "" port 587

Then I found [this](https://github.com/thoughtbot/factory_girl/issues/543). Changed my factories and tests to be like that one, since it's a closed issue and I assume it works. I still get the same error. Also if I change create to build, I'm getting this:

>   1) UserBuilding should associate the user with the building
>     Failure/Error: @user.buildings << @building
>     
>     NameError:
>       uninitialized constant User::Buildings

Which I don't really get, considering my setup seems to be the same as the one in the issue I linked.
Anyway, any idea what the create error is? ~~It makes no sense to me, what does port 587 have to do with it?~~

**EDIT:** I've traced the error. This is legacy code, by the way. It seems that the person who created the application has devise sending emails when a user is created. In the test environment, it's configured so that it won't try to send it through the internet, it'll just send through localhost and keep it in an array. For some reason it fails when it gets to this:

`TCPSocket.open address, port`
in smtp.rb

In fact, now it's causing that error even when I use build instead of create!

Just to be clear, here are my factories:

`FactoryGirl.define do`
`  factory :inspection do`
`    notes "Inspection Notes"`
`    building`
`    after(:create) do |inspection|`
`            inspection.building = FactoryGirl.build(:building)`
`    end`
`  end`

`  factory :user do`
`    name "Filip"`
`    email "filip@redacted.com"`
`    password "redacted"`
`  end`

`  factory :building do`
`    name "Test Building"`
`    address "0 Test St"`
`  end`

`  factory :user_building do`
`    user`
`    building`
`  end`

`  # factory :user_building do`
`  #   after(:create) do |user_building|`
`  #           user_building.user << FactoryGirl.build(:user)`
`  #           user_building.building << FactoryGirl.build(:building)`
`  #   end`
`  # end`

`end`

and my user_building_spec file:

`require 'rails_helper'`
`describe UserBuilding, :type => :model do`
`  before :each do`
`    @user = build(:user)`
`    @building = build(:building)`
`    @user.buildings << @building`
`  end`

`  it "should associate the user with the building" do`
`    expect(@user.name). to eq("Filip")`
`    expect(@building.name).to eq("Test Building")`
`    expect(@user.buildings).to eq(1)`
`  end`

`  context "Connecting Users to Buildings through 1 factory" do`
`    before :each do`
`      @user_and_building = build(:user_building)`
`    end`

`    it "should create a new user and building and associate them" do`
`      expect(@user_and_building.user.name).to eq("Filip")`
`      expect(@user_and_building.building.name).to eq("Test Building")`
`    end`
`  end`

`end`

**Comment by joshuaclayton** [comment]
You're correct re: email. A Google search for ["port 587"](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=port%20587) should point you in the right direction.

As for the `User::Billings` issue, it looks to me there's an issue with the associations in `UserBuildings` (specifically, the associations look pluralized, which I don't believe you'd want for a `belongs_to`).

**Comment by geleiademocoto** [comment]
Yes, but the thing is devise is configured to not really send emails through the internet, it just "pretend" sends, so there shouldn't be a connection error. That's why it's confusing to me.  

As for the associations being pluralized, do you mean the model definition? This:

```
class UserBuilding < ActiveRecord::Base
belongs_to :users
belongs_to :buildings
end
```

I'll look into it. Like I said, it's legacy code, so I'm wary of changing it, but I'll contact the person who wrote it and ask why they decided to pluralize it. I assumed that it was because it can belong to multiple users after all. Not so sure about the multiple buildings though, it seems to me it should be one building per UserBuilding association. Anyway that's a DB modeling issue so it's unrelated to factory_girl. Thanks for the answer.
