### ISSUE TITLE
Multiplication not existing anymore in FactoryGirl on random number

### ISSUE THREAD

**Issue by Loschcode** [thoughtbot/factory_girl#920]
```
require 'rails_helper'
require 'faker'
require 'support/helpers/global'
include Helpers::Global

FactoryGirl.define do

  factory :admin, :class => User do

  end

  factory :shopkeeper, :class => User do

  end

  factory :customer, :class => User do

    fname                  "Customer"
    lname                  "N#{next_number(:customer)}"
    gender                 random_gender
    username               "Customer#{next_number(:customer)}"
    email                  "customer#{next_number(:customer)}@customer.com"
    password               '12345678'
    password_confirmation  '12345678'
    role                   :customer
    tel                    Faker::PhoneNumber.phone_number
    mobile                 Faker::PhoneNumber.cell_phone
    birth                  rand * Time.now.to_i #"1970-02-12" #random_date

  end

end
```

I'm trying to get the `birth                  rand * Time.now.to_i` line to work but this error appears `/Users/Loschcode/Google Drive/projects/panda-lo/website/spec/factories/users.rb:28:in `block (2 levels) in <top (required)>': undefined method `*' for #<FactoryGirl::Declaration::Implicit:0x007fcc32caa700> (NoMethodError)`

I tried to find a way around it but it's like the multiplication doesn't exist anymore. I'm using `binding.pry` to troubleshoot this and there's no error whatsoever ... Only during the test. When i remove this specific line everything works fine.

Am I doing something wrong ?

My test bundle

```
group :development, :test, :staging, :local do
  gem "factory_girl_rails"
  gem "rspec-rails", "~> 3.0"
  gem "capybara"
  gem "database_cleaner"
  gem "pry-rails"
end

**Comment by joshuaclayton** [comment]
@Loschcode you'll want to wrap the values in `{` and `}` so they're recognized as block syntax and evaluated every time the factory is run, e.g.

```ruby
factory :customer, class: "User" do
  birth { Time.current - (rand 60.years) } # gives you someone between 0 and 60 years old
end
```

For *any* interpolation in a factory, you'll want to use the block syntax.

Hope this helps! I'll close this for now, but if you run into issues, don't hesitate to comment on this thread.
