### ISSUE TITLE
Documentation for running FactoryGirl.lint in before(:suite)

### ISSUE THREAD

**Issue by Ross-Hunter** [thoughtbot/factory_girl#923]
So it's not recommended to run `FactoryGirl.lint` in a `before :suite` because it will slow down running individual tests, but RSpec can be configured to not run linting if only running an individual test using `config.files_to_run.one?`.

```ruby
# spec/spec_helper.rb
config.before :suite do
  DatabaseCleaner.strategy = :transaction
  DatabaseCleaner.clean_with :truncation

  begin
    DatabaseCleaner.start
    FactoryGirl.lint unless config.files_to_run.one?
  ensure
    DatabaseCleaner.clean
  end
end
```

This is simpler for my use case (and probably many others) than setting it up as a separate task. However I can only confirm that this works with the latest Rspec, while the separate task doesn't even need to be 'compatible' with a test suite.

Should I try to add this to the documentation, or should I just write a blog post about it? Seems like it would be helpful to a lot of people, but it might be more confusing overall than just sticking to the separate task as the recommended linting configuration.

**Comment by joshuaclayton** [comment]
Hey @Ross-Hunter! I'd never seen that before - pretty neat. I think a blog post about it might be a good first start. As FG has matured, I've found I lean more towards having a bunch of people try things out/put solutions through their paces before making recommendations, and this seems like a good one for others to try. I'm happy to do some promotion of the post on my personal account and internally on @thoughtbot projects to see how it behaves.

As an aside - if there's literally only one test (weird situation, I know!), would this get run? (More for my personal understanding than anything else 😄)

**Comment by joshuaclayton** [comment]
All that said - if this goes well and people are happy with the solution, I'm happy to merge a PR in the coming weeks!

**Comment by myronmarston** [comment]
FWIW, `config.files_to_run` predates my involvement in RSpec (which started in 2010-11, IIRC), so it's definitely a long-term, stable API.  Our generated `spec_helper.rb` does something similar with `files_to_run.one?`:

https://github.com/rspec/rspec-core/blob/v3.4.4/lib/rspec/core/project_initializer/spec/spec_helper.rb#L69-L77

> As an aside - if there's literally only one test (weird situation, I know!), would this get run? (More for my personal understanding than anything else 😄)

Yes.  The `before(:suite)` hook always gets invoked before the first spec is run, regardless of how many specs have been loaded.

**Comment by joshuaclayton** [comment]
@myronmarston 👍  you rock sir! Thanks for the context.
