### ISSUE TITLE
override an association's attributes with another association

### ISSUE THREAD

**Issue by levsero** [thoughtbot/factory_girl#926]
assuming two factories that both associate with a single factory but also one to the other for example:
```
factory :merchant do
  store
  register
end

factory :register do
  store
end
```
I would like to for the merchant to override the store attribute in register with its own associated store when it creates the register, similar to how it can override an attribute with a string, so something like this:
```
association :register, store: store
```
but instead this raises an error `Attribute already defined: store`.
Currently as a workaround to this I'm using
```
after :create, :build do | merchant |
  shift.merchant ||= create(:register, store: merchant.store)
end

after :stub do | merchant |
  merchant.register ||= build_stubbed(:register)
end
```

**Comment by stoivo** [comment]
I would like a fix for this too, have a issue very like your.

**Comment by joshuaclayton** [comment]
@levsero in these cases, I've done this:

```ruby
factory :merchant do
  store { register.store }
  register
end
```

In general, having FG infer these sorts of relationships is incredibly difficult due to the various types of relationships and names, so it requires a tad more long-hand to get it to work.
