### ISSUE TITLE
Gem cannot be installed in Rubies older than 2.2.2 due to activesupport

### ISSUE THREAD

**Issue by danielkza** [thoughtbot/factory_girl#929]
```
$ ruby --version
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
$ gem install factory_girl
ERROR:  Error installing factory_girl:
	activesupport requires Ruby version >= 2.2.2.
```

This happens because activesupport 5 was released without support for older rubies. I'm seeing the same issue in older gems and have not found a good solution: restricting the maximum version will break compatibility with Rails 5 projects. It seems the only sane workaround is using a fake native extension that just installs the correct activesupport version depending on the Ruby version being used.

**Comment by danielkza** [comment]
I missed #928 before creating this, but that approach is probably not good enough: as I mentioned, adding a maximum bound to the activesupport dependency will break Rails 5 projects.

**Comment by joshuaclayton** [comment]
@danielkza thinking about this, I'd argue this is an issue with Bundler and dependency resolution failing, and not something with FactoryGirl specifically.

FG has declared AS >= 3 as workable, but AS 5 has declared Ruby < 2.2 unworkable. It seems like Bundler would be responsible for finding the combination of latest FG and AS based on the current Ruby version, and doing the right thing. A gem shouldn't be required to take into account the supported versions of every dependency, across every release, and modify its supported versions to account for it.

Not sure if this is on their radar, but it might be worth bringing up in an issue there.

In the meantime, if you install the latest 4.X AS, you should be able to install FG:

```sh
gem install activesupport --version 4.2.6
gem install factory_girl
```

For actual projects, I'd recommend locking to the appropriate version of AS in the `Gemfile`, which will resolve the issue and move the responsibility from the gem authors (who can't control every Ruby+gem version) to the developers who have restrictions on the version of Ruby they deploy with.

Please let me know if installing the older version of AS doesn't work, but I was able to install 2.1.8 cleanly, reproduce the failure you were seeing, install v4.2.6 of AS, and install FG successfully.

**Comment by danielkza** [comment]
@joshuaclayton My test wasn't using Bundler at all, only Rubygems. It is the one that does the dependency resolution, with version constraints possibly coming from a Gemfile or gemspec.

While I agree that it should take the Ruby version in consideration while picking the dependency version, it currently does not, and probably will not in the near future. It is unfortunate, but a fact, and it's very likely many people will hit that breakage regardless of which software is at fault.

I believe it would be a good idea to add a mention of this somewhere in the docs so people are likely to find it when they inevitably run into the problem.

**Comment by goughy000** [comment]
I was kind of hoping that my merge would be accepted and then it would be removed on the next major version of FG.

We are already locking down the activesupport versions in Gemfiles but it seemed like a workaround

**Comment by joshuaclayton** [comment]
@goughy000 @danielkza I just opened #930 adding documentation in the README, moving around installation to encourage Bundler, then manual install, with the caveat that the latest AS may break on older Rubies.

Please let me know if you think the explanation in the docs is clear, or if you have any other thoughts on how best to document this breakage.

My hope, honestly, is that very few people attempt to install by hand, or if they do, they're also in a position to upgrade their Ruby (since it seems like it's outside of a specific project anyway).

**Comment by goughy000** [comment]
Looks good to me!

**Comment by danielkza** [comment]
@joshuaclayton The problem also happens if you use Bundler. For example, if you're running Debian stable you have Ruby 2.1. If a project of a gem that isn't using Rails includes factory_girl in it's Gemfile, and you attempt to do a `bundle install`, it will break.

**Comment by goughy000** [comment]
Just add 
```ruby
gem 'activesupport', '< 5'
```
To your Gemfile

**Comment by danielkza** [comment]
@goughy000 That's my current solution, with a guard to allow AS 5 on new enough Rubies:

```ruby
if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.2.2')
  gem 'activesupport', '< 5'
end
```
