### ISSUE TITLE
Problem with skipping callbacks after upgrade to Rails

### ISSUE THREAD

**Issue by pawandubey** [thoughtbot/factory_girl#931]
We have a model `Company` with an `after_create` callback.
```ruby
class Company < ApplicationRecord
  after_create :do_something
  
  # other methods
  def do_something
     # work
  end
end
```
In our factories, we are skipping callbacks like so:
```ruby
after(:build) do |company|
      company.class.skip_callback(:create, :after, :set_default_company_preference)
end
```

This worked fine and all our tests pass on Rails 4.2, but after upgrading to Rails 5, we are getting 
```
ArgumentError:
       After create callback :do_work has not been defined
```

This is happening with all our models in which we have callbacks defined. Did Rails/Factory Girl change something in an unexpected way?

**Comment by mgrunberg** [comment]
Looking at the [changelog](https://github.com/rails/rails/blob/5-0-stable/activesupport/CHANGELOG.md) of Rails 5:

```
ActiveSupport::Callbacks#skip_callback now raises an ArgumentError if an unrecognized callback is removed.
```

[Here](https://github.com/rails/rails/pull/19029) is the pull request with the message you are seeing.

So I think that the callback ```:do_work``` not exists and in previous versions, the skip_callback call was failing silently

**Comment by baramik** [comment]
Have some promlems here also. Callback is defined in model. But tests being failed for some reason

**Comment by joshuaclayton** [comment]
@pawandubey FactoryGirl's callbacks are entirely decoupled from ActiveRecords', apart from the fact that FG calls `save!`, which will trigger callbacks. Apart from that, FG doesn't interfere/interact whatsoever. This is very likely an issue with the upgrade to Rails 5 (you'd probably be able to confirm by calling `Company.skip_callback` by hand in the console, without using FG).

**Comment by savmac** [comment]
I came across this issue as well after upgrading to Rails 5. What I was able to figure out is that after creating one instance of a factory, the callback method is no longer defined on the model for any subsequent instances that are created. Rails 4 ignored this but Rails 5 raises the argument error. You can confirm in the console by calling `Foo.skip_callback(:create, :after, :bar)` and it will work the first time but then fail if you do it again.

I was able to get test passing again by changing the factory callback to:
```
after(:build) do |foo|
  class << foo
    def bar; true; end
  end
end
```
[Which I found here](http://stackoverflow.com/a/22916595/2638953)

Not sure if this is the best approach if anyone has any suggestions. I suppose you could also call `set_callback` in an `after(:create)` factory callback.

**Comment by s2t2** [comment]
Try passing `, raise: false` to make the error message go away while keeping the callback setting/skipping functionality:

```` rb
after(:build) do |company|
  company.class.skip_callback(:create, :after, :set_default_company_preference, raise: false)
end

**Comment by wedgemartin** [comment]
Hello from many years later.. Using current Rails, factorybot, lots of things I probably shouldn't be, but it's an old project.. the only thing I found to work for me in order to get Rspec + factorybot tests to run was to set the callbacks to :async when the Rails.env is test.  Tried everything here and then some, but nothing seemed to work.
