### ISSUE TITLE
FactoryGirl.create issues “LocalJumpError: no block given (yield)” with Rails 5

### ISSUE THREAD

**Issue by marcocanderle** [thoughtbot/factory_girl#933]
Hello,

I'm in the process of upgrading my app to Rails 5 When running the tests with rails 5 enabled I started to get "LocalJumpError: no block given (yield)" on several object creation sentences like this one:

    let!(:entity) { create(:entity) }

This started to happen after I upgraded to Rails 5.0.0 I tried using build instead of create on that line and the error doesn't show up in that case so it seems there is something wrong with the FactoryGirl.create method.

Has anyone got a similar issue or maybe knows if this is a known bug on FactoryGirl gem?

My Entity factory is this one:

    FactoryGirl.define do
      factory :entity do
        entity_type 'A'
        account { create(:account) }
        ilk []
        after(:build) do |entity|
          entity.names << build(:name)
          entity.addresses << build(:address)
        end

        trait :incomplete do
          incomplete true
        end
      end

My Gemfile looks like this: https://jpst.it/Lb6N

Thanks!

**Comment by marcocanderle** [comment]
I keep debugging and identified the issue as apparently being on the mongoid gem. Here's the corresponding ticket I opened for it. You'll need a JIRA account with access to mongoid project: https://jira.mongodb.org/browse/MONGOID-4302

The details of this ticket are that by running rspec -b to see the trace, I identified the issue on this line on the mongoid gem:

https://github.com/mongodb/mongoid/blob/master/lib/mongoid/clients/options.rb#L25

The issue disappears if I replace that line (yield self) with just:

    self

I'm not sure however if this is a feasible fix, so I opened the ticket mentioned before to get mongoid's feedback and see what can be done.

I'll update again when I get any feedback.

**Comment by joshuaclayton** [comment]
@marcocanderle can you provide a backtrace of the failure?

**Comment by marcocanderle** [comment]
Here's the backtrance: https://justpaste.it/wmo9

I also opened this ticket at mongoid project (you'll need a JIRA account with access to Mongoid project) as I'm currently not sure about the source of this issue, between this gem, mongoid or my code : https://jira.mongodb.org/browse/MONGOID-4302 

Thanks!

**Comment by joshuaclayton** [comment]
@marcocanderle hmm, interesting.

In cases like this, the first things I recommend are:

1. replace FactoryGirl usage with traditional ORM/ODM usage - in this case, it'd be Mongoid
2. replace some of the fancy RSpec features, like `let`, with normal Ruby (e.g. extract to a method, do local assignment to the symbol in `let`)

Both of those help isolate where things are cropping up.

Did you happen to upgrade RSpec in the process? Is there any RSpec+Mongoid config files that are now invalidated? Are you also upgrading Mongoid?

For major version bumps, I've found what works best is upgrade in isolation as much as possible, to reduce moving parts/things that could break along the way.

For this error in particular, it looks like there's some odd Mongoid configuration changes somewhere that are interfering, although it's hard to tell exactly where that might be without access to the whole project. As I mentioned, I'd start isolating some of the various aspects, get it to a point where it works, and slowly fold in some of the changes to understand what's being added that breaks things.

Hope this helps, and looking forward to hearing what you find out!

**Comment by marcocanderle** [comment]
@joshuaclayton thanks for you suggestions. It actually helped me realized the issue was on our local fork of the mongoid-token gem... A lot of time later than I would have liked but we are there. 

Thanks a lot for your help and time!
