### ISSUE TITLE
NoMethodError: undefined method `save!' for nil:NilClass

### ISSUE THREAD

**Issue by Kris-Simpson** [thoughtbot/factory_girl#937]
Hello guys!

Today I found very odd bug in (I think so) FactoryGirl.
I tested it in new app with these structure:

Two models:
```ruby
class Tap < ActiveRecord::Base
end
```
and
```ruby
class Comment < ActiveRecord::Base
  belongs_to :tap
end
```
Also have factory for `comment`:
```ruby
FactoryGirl.define do
  factory :comment do
  end
end
```
And some test  (our main target is to create `comment` factory):
```ruby
require 'rails_helper'
RSpec.describe Comment, type: :model do
  it 'has a valid factory' do
    FactoryGirl.create(:comment)
  end
end
```

In line `FactoryGirl.create(:comment)`  raises the error:
```ruby
  1) Comment has a valid factory
     Failure/Error: FactoryGirl.create(:comment)
     
     NoMethodError:
       undefined method `save!' for nil:NilClass
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/configuration.rb:18:in `block in initialize'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/evaluation.rb:15:in `create'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/factory.rb:42:in `run'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:28:in `run'
     # /home/kris/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/comment_spec.rb:5:in `block (2 levels) in <top (required)>'
```
This bug odd because factory raise error only for records with `belongs_to` association named `tap`. So if I rename my model `tap` to `some_model`, factory will be work. If I add `belongs_to :tap` association to any another model it will fail too.

What it can be? Thank you very much.

Ruby: 2.3.1
Rails: 4.2.7
Rspec-rails: 3.5.1
Factory_girl_rails: 4.7.0

**Comment by joshuaclayton** [comment]
@Kris-Simpson this is likely because Ruby provides [`Object#tap`](http://ruby-doc.org/core-2.3.1/Object.html#method-i-tap); my guess is that there's an issue with this association name that you're running into. This will likely also cause you issues outside of FactoryGirl; my recommendation would be to rename the association entirely.

**Comment by vnhnhm** [comment]
https://stackoverflow.com/a/5205665/5025116
