### ISSUE TITLE
add new strategy for associations

### ISSUE THREAD

**Issue by DimasJok** [thoughtbot/factory_girl#948]
The problem is that, I have two models(A, B) and they are related to a third another model(C) so if I add an association to model A and B (association :author, factory: :user, strategy: :build)
```ruby
class A < ActiveRecord::Base
  belongs_to :C
end

class B < ActiveRecord::Base
  belongs_to :C
end

class C < ActiveRecord::Base
  has_many :A
  has_many :B
end

FactoryGirl.define do
  factory :a, class: A do
    association :C, factory: :c, strategy: :build
  end
end

FactoryGirl.define do
  factory :b, class: B do
    association :C, factory: :c, strategy: :build
  end
end

FactoryGirl.define do
  factory :c, class: C do
  end
end

FactoryGirl.define do
  factory :d, class: D do
    association :A, factory: :a: , strategy: :build
    association :B, factory: :b, strategy: :build
  end
end
```
So when I write **create(:d)**, Factory **:c** is creating twice therefore it's showing me a uniqueness error

So I think if factory **:c** should'nt be created when this line is exec **association B, factory: :b, strategy: :build**, because **association :A, factory: :a, strategy: :build** already created

Someone got this error and this worked for him: https://gist.github.com/hiasinho/0ed0567dfc091047dc26 but I don't know how to implement on my project

Why factory_girl does not have some strategy that works like this method first_or_create?

**Comment by joshuaclayton** [comment]
@DimasJok something similar to `first_or_create` causes non-determinism in the test suite, which I outline here: https://github.com/thoughtbot/factory_girl/issues/683#issuecomment-248977879

My recommendation would be to build this up manually or write vanilla Ruby to manage building up more complex data structures, based on the pattern(s) required by your codebase.
