### ISSUE TITLE
Pass object to controller ?

### ISSUE THREAD

**Issue by Sashkan** [thoughtbot/factory_girl#949]
I'm working on my very first test using FactoryGirl, rspec and Capybara, and I was wondering: How do I pass a freshly created object to its testing method ?

So far I managed to create my factories, and my test. It creates a user, assigns him an ```onboard_token```, and then visits my page. On controller side, I'm retrieving the User with the ```find_by_onboard_token``` method.

The problem is, it cannot find such a user
```
token = params[:token]
!User.where(onboard_token: token).empty?
```
I made sure ```params[:token]``` was present, but still, it's kinda hard to figure out the relationship between objects created in tests and their match in controller.

Here is my test:
```rb

RSpec.describe UsersController, type: :controller do
  render_views

  before(:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
  end

  describe "GET #onboard", :js => true do

    it "simulates creator onboard" do
      visit onboard_path(:token => @user.onboard_token)
      page.execute_script('$(\'.two-parts-slide\').css(\'margin-left\', \'-100%\');')
      fill_in('whoami', with: 'Test Model')
      fill_in('whoami2', with: 'Test Model')
      fill_in('pw1', with: '12345678')
      fill_in('pw2', with: '12345678')
      if page.has_selector?('#agreeterms')
        page.execute_script('$(\'#agreeterms\').prop(\'checked\', true);')
      else
        find('#agreeterms', :match == :first).trigger('click')
      end
      page.execute_script('$(\'#submit-welcome\').click();')
      expect(@user.active).to eq(true)
    end
  end


end


```

Now, I'm not even sure this comes from FactoryGirl, it might as well just come from my lack of experience with tests. Sorry if this sounds silly !

**Comment by prasadsurase** [comment]
@Sashkan This is not related to FactoryGirl. You are testing the controllers the wrong way. For controller tests, you need to pass the params to the controller action being tested without interacting through the UI. Please refer [rspec-controller-tests](https://www.relishapp.com/rspec/rspec-rails/v/3-5/docs/controller-specs) for more details.

**Comment by joshuaclayton** [comment]
@Sashkan for tests exercising JavaScript, I've found Capybara + RSpec features to be a better path to go down. https://robots.thoughtbot.com/write-reliable-asynchronous-integration-tests-with-capybara might be a good start.
