### ISSUE TITLE
NoMethodError: undefined method `campaign=' for #<NativeAd:0x000000058fe5d0>

### ISSUE THREAD

**Issue by davidyin1212** [thoughtbot/factory_girl#951]
Hello I'm not sure if this is an issue or if I'm just doing something wrong but I'm getting an issue when attempting to create an association. Here are my factories:
```
FactoryGirl.define do
  factory :native_ad do
    association :campaign, factory: :campaign, strategy: :build_stubbed
  end
end
```

```
FactoryGirl.define do
  factory :campaign do |f|
    name 'test'
    is_draft true

    trait :with_native_ads do
      ignore do
        campaign_count 5
      end

      after(:build) do |campaign, evaluator|
        build_list(:native_ad, evaluator.campaign_count, campaigns: [campaign])
      end
    end
  end
end
```

but when I run `@native_ad = build_stubbed(:native_ad)` it throws 
`NoMethodError: undefined method `campaign=' for #<NativeAd:0x000000058fe5d0>` Error

Also when i actually try to run `@campaign = build(:campaign, :with_native_ads, campaign_count: 5)` I get 
```
Failure/Error: build_list(:native_ad, evaluator.campaign_count, campaigns: [campaign])

     NoMethodError:
       undefined method `campaign=' for #<NativeAd:0x00000003458d98>
```
I've been going through this problem now for a while and I'm really stuck thanks in advance

**Comment by joshuaclayton** [comment]
@davidyin1212 it looks like `NativeAd` doesn't have the association declared on the model. Can you confirm that's the case, and the test environment isn't missing any migrations that should've been run?

**Comment by davidyin1212** [comment]
@joshuaclayton Ok so i looked through the code and I realized that we actually use a has_many through relation rather than a has_and_belongs_to_many relation. So I rewrote the factories as such:

```
FactoryGirl.define do
  factory :campaign do |f|
    name 'test'
    association :user, factory: :user, strategy: :build_stubbed
    bid_type 'cpm'
    is_draft true
    smart_targeting true
    platform nil
    campaigns_native_ads []

    trait :with_native_ads do
      ignore do
        campaign_count 5
      end

      after(:build) do |campaign, evaluator|
        puts "CAMPAIGN: " + campaign.to_s
        build_list(:campaigns_native_ad, evaluator.campaign_count, campaign: campaign)
      end
    end
  end
end
```

```
FactoryGirl.define do
  factory :campaigns_native_ad do
    association :campaign, factory: :campaign, strategy: :build_stubbed
    association :native_ad, factory: :native_ad, strategy: :build_stubbed
  end
end
```

So the corresponding models are campaign which contains a `has_many :campaigns_native_ads` relation and for CampaignsNativeAd I have this:
```
class CampaignsNativeAd < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :native_ad
```
So currently it no longer crashes however when I try to access campaign.campaigns_native_ads it says its blank and I'm not sure why I'm still fairly new with this so I'm not completely sure if what I'm doing is actually correct. Thanks in advance

**Comment by davidyin1212** [comment]
@joshuaclayton do you know what's going on here thanks

**Comment by joshuaclayton** [comment]
@davidyin1212 since you're creating data in the callback, you might have to reload the campaign you're creating so it refreshes the data. Rails is unable to mutate internal state based on external actors (in your case, `build_list(:campaigns_native_ad, evaluator.campaign_count, campaign: campaign)`), so `campaign` doesn't see the results of the associated records being created. `campaign#reload` will help there.

In general, GitHub issues are not a place for debugging code, nor am I able to look over your code for free to help debug. StackOverflow might be a better place for that.
