### ISSUE TITLE
Set updated_at column on model when using build_stubbed

### ISSUE THREAD

**Issue by coorasse** [thoughtbot/factory_girl#954]
I didn't see a previous issue regarding that and I'd like to open a discussion about this point.
When using `build_stubbed` to generate a model which "pretends" to be persisted on the database the column `updated_at` is `nil`. build_stubbed correctly sets the `created_at` column but not the `updated_at`. When you really persist an object on DB (in Rails) also the column `updated_at` is set so I'd expect it to have a value.

**Comment by joshuaclayton** [comment]
@coorasse that's an excellent point, and agreed that there should be consistency.

Want to open up a PR testing and implementing this behavior? If you need help getting started, please let me know!

**Comment by prasadsurase** [comment]
I am using factory_girl(4.7.0) with mongoid(5.1.4). When using build_stubbed, both created_at and updated_at aren't populated and are nil.

```ruby
2.3.0 :002 > r = FactoryGirl.build_stubbed :round
 => #<Round _id: 57ff92195f10de2aa59114b3, created_at: nil, updated_at: nil, name: "Y-find", from_date: 2016-10-12 21:27:49 UTC, end_date: 2016-11-11 23:47:46 UTC, status: "open"> 
2.3.0 :003 > r.persisted?
 => true 
2.3.0 :004 > r.new_record?
 => false 
```

**Comment by schmijos** [comment]
👍
