### ISSUE TITLE
Could not find table 'xxxx' when running `rake db:migrate RAILS_ENV=test`

### ISSUE THREAD

**Issue by FX-HAO** [thoughtbot/factory_girl#972]
Hi!

I get the following error:

    ActiveRecord::StatementInvalid: Could not find table 'spree_roles'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:501:in `table_structure'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:375:in `columns'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attributes.rb:93:in `columns'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/attributes.rb:98:in `columns_hash'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:969:in `block in create_binds'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:967:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:967:in `partition'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:967:in `create_binds'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:954:in `build_where'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:584:in `where!'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:574:in `where'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:84:in `find_by'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:213:in `find_or_create_by'
    /usr/local/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:6:in `find_or_create_by'
    /Users/haofuxin/shundaojia/shundao-backend/spec/factories/users.rb:30:in `block (2 levels) in <top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `factory'
    /Users/haofuxin/shundaojia/shundao-backend/spec/factories/users.rb:28:in `block in <top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
    /Users/haofuxin/shundaojia/shundao-backend/spec/factories/users.rb:1:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:19:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
    /usr/local/lib/ruby/gems/2.3.0/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
    /Users/haofuxin/shundaojia/shundao-backend/config/environment.rb:5:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
    /usr/local/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
    /usr/local/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
    Tasks: TOP => db:migrate => environment
    (See full trace by running task with --trace)

It seems try to load definitions during initialization. Any idea?

Thanks!

**Comment by tom-lord** [comment]
Is your test database migrated?

    RAILS_ENV=test rake db:migrate

**Comment by FX-HAO** [comment]
It is my fault.
