### ISSUE TITLE
Question: using `#association` with traits

### ISSUE THREAD

**Issue by rstacruz** [thoughtbot/factory_girl#976]
I see that you can:

```rb
factory :book do
  association :publisher, factory: :company
end
```

But can you add a trait?

```rb
factory :book do
  association :publisher, factory: [:company, :is_publisher]
end
```

**Comment by mxie** [comment]
Yup! Here's in example in the spec: https://github.com/thoughtbot/factory_girl/blob/8a65569f102ac2593e7c73bd029d5072e4641af8/spec/acceptance/traits_spec.rb#L696-L698.

**Comment by mxie** [comment]
Closing - feel free to reopen if you have any issues using traits this way.
