### ISSUE TITLE
Is there a load order dependency for factories?

### ISSUE THREAD

**Issue by tgmerritt** [thoughtbot/factory_girl#977]
I stumbled upon an interesting issue with FactoryGirl writing some tests today.  I believe there is a load order on factories, and that unlike Rails where say all files are loaded at "boot" and then available (classes, etc.), FactoryGirl seems to lazy-load factories in alphabetical order.

This is what I'm experiencing, though my assessment of the situation could be incorrect.

I'm getting a pretty common error when you setup a factory incorrectly (misspell, etc.):

`/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/factory_girl-4.5.0/lib/factory_girl/registry.rb:24:in `find': Factory not registered: jobtype (ArgumentError)`

However, the factory is correctly defined.

Here is a screenshot showing what DOES NOT work:

[
<img width="684" alt="screen shot 2016-12-23 at 5 36 23 pm" src="https://cloud.githubusercontent.com/assets/1245864/21450071/f0910842-c936-11e6-8750-5cd3e1cdefd8.png">
](url)

When I uncomment the jobtype line and run the test, I get the factory not registered error above.  But the CUSTOMER factory goes through just fine.  The only reason I can see is that job alphabetically comes before jobtype and the files are loaded top-down in the folder.

When I create the jobtype before the job records as in the following screenshot:

<img width="1044" alt="screen shot 2016-12-23 at 5 38 24 pm" src="https://cloud.githubusercontent.com/assets/1245864/21450092/2c2201c2-c937-11e6-9bf3-08e116cf81e4.png">

Everything works just fine.  Jobtype is created and sent into job, customer is created at the same time that job is invoked, and the tests pass as they should.

This proves to me that there is nothing wrong with the way I've configured the jobtype factory itself.  It's rather the order in which I call them that matters.

Using gem 'factory_girl_rails', '~> 4.5.0'

rails_helper.rb:

```
ENV["RAILS_ENV"] ||= 'test'
require 'spec_helper'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'rspec/api_helpers'
# Add additional requires below this line. Rails is not loaded until this point!

Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }

ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"

  config.use_transactional_fixtures = false
  config.use_transactional_examples = false

  config.include Rails.application.routes.url_helpers

  config.infer_spec_type_from_file_location!

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:transaction)
  end

  config.before(:each) do
    DatabaseCleaner.strategy = :transaction # ActiveRecord
    # DatabaseCleaner.clean_with(:deletion)
  end

  config.before(:each, :js => true) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:transaction)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.include Rspec::ApiHelpers, type: :api #apply to all spec for apis folder
end
```

Is this expected behavior, a config option I missed, or perhaps a config option should be added or documentation improved?

**Comment by joshuaclayton** [comment]
@tgmerritt when declaring attributes, you'll want to wrap them in a block when the value is dynamic (e.g. timestamps, associations); otherwise, you'll run into issues like this.

Because the factory and association name are the same, you can use the shorthand declaration for associations:

```ruby
# shorthand association syntax
factory :job do
  # ... other attributes
  customer
  jobtype
end
```

Alternatively, here's the block version:

```ruby
# alternate block syntax for values that will change
factory :job do
  # ... other attributes
  customer { create(:customer) }
  jobtype { create(:jobtype) }
end
```

As I mentioned, the block version is also necessary if you want timestamps to work; otherwise, the value will be set to the timestamp relative to when the factories were loaded:

```ruby
factory :job do
  approved_at Date.current # bad! It'll be the same timestamp throughout the test suite
  approved_at { Date.current } # good! It'll be evaluated every time the factory is built or created
end
```
