### ISSUE TITLE
API to check registered traits on a factory

### ISSUE THREAD

**Issue by ened** [thoughtbot/factory_girl#998]
For my projects I'm using  simple spec to ensure all factories are valid:

```
FactoryGirl.factories.each do |factory|
  describe "The #{factory.name} factory" do
    it 'is valid' do
      f = FactoryGirl.build(factory.name)
      f.save!
      expect(f).to be_valid
    end
```

It would be great to extend it with checks for all registered traits on each factory object. This workaround helps:
```
    factory.send(:definition).defined_traits.collect(&:name).each do |trait|
      describe "trait #{trait}" do
        it 'is valid' do
          f = FactoryGirl.build(factory.name, trait)
          f.save!
          expect(f).to be_valid
        end        
      end
    end
```

**Comment by joshuaclayton** [comment]
@ened I'd recommend taking a look at the overview of [linting factories](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#linting-factories), especially the section on traits:

```ruby
FactoryGirl.lint traits: true
```

This should do exactly what you'd like to accomplish.

**Comment by ened** [comment]
Classic RTFM. Thank you.

**Comment by joshuaclayton** [comment]
@ened no worries 😄  - you're welcome!
